import { adjustErosion, attachCards, chooseCards, chooseOption, draw, grantKeywords, grantSignalAlias, modifyStats, moveCards, reorderSignalZone, revealTop, selected, setOrientation, source, when, } from '../../engine/actions';
import type { CardBehavior } from '../../engine/card-behavior';
import { createVanilla } from '../shared/vanilla';
const field = (feature: string) => ({ player: 'controller' as const, zone: 'battlefield' as const, feature });
const BP01_001: CardBehavior = { cardNo: 'BP01-001', coverage: 'complete', onEnter(c) { c.enqueue(chooseCards({ bind: 'signals', prompt: '可以消除2张同色信号球发动出场能力', min: 0, max: 2, optionalExact: true, selector: { player: 'controller', zone: 'signal' }, constraint: 'sameSignalColor', then: [moveCards(selected('signals'), 'graveyard'), revealTop(5, 'controller', 'top5'), chooseCards({ bind: 'grayRaven', prompt: '选择费用合计6及以下的〈灰鸦小队〉角色出场', min: 0, max: 5, maxTotalCost: 6, selector: { player: 'controller', zone: 'processing', cardType: '角色牌', feature: '灰鸦小队' }, poolBinding: 'top5', then: [moveCards(selected('grayRaven'), 'battlefieldReady')], remainder: 'deckBottom', preserveSelectionOrder: true })] })); } };
const BP01_002: CardBehavior = { cardNo: 'BP01-002', coverage: 'complete', continuous(c) { const ready = c.query.count(field('里')) > 0 && c.query.count(field('丽芙')) > 0; return { cost: ready ? -3 : 0 }; }, onEnter(c) { c.enqueue(chooseCards({ bind: 'signals', prompt: '可以消除2张同色信号球获得突进与充能0', min: 0, max: 2, optionalExact: true, selector: { player: 'controller', zone: 'signal' }, constraint: 'sameSignalColor', then: [moveCards(selected('signals'), 'graveyard'), grantKeywords(source(), ['突进', '充能 -1'])] })); } };
const BP01_003: CardBehavior = { cardNo: 'BP01-003', coverage: 'complete', onEnter(c) { c.enqueue(chooseCards({ bind: 'ally', prompt: '可以将我方1张〈灰鸦小队〉角色返回手牌', min: 0, max: 1, selector: { ...field('灰鸦小队'), excludeInstanceId: c.source.instanceId }, then: [moveCards(selected('ally'), 'hand'), chooseCards({ bind: 'return', prompt: '选择战场1张费用5及以下角色返回手牌', min: 1, max: 1, selector: { player: 'any', zone: 'battlefield', maxCost: 5 }, then: [moveCards(selected('return'), 'hand')] })] })); } };
const BP01_004: CardBehavior = { cardNo: 'BP01-004', coverage: 'complete', onEnter(c) { c.enqueue(chooseCards({ bind: 'discard', prompt: '丢弃1张手牌', min: 1, max: 1, selector: { player: 'controller', zone: 'hand' }, then: [moveCards(selected('discard'), 'graveyard'), chooseCards({ bind: 'cost', prompt: '选择费用区1张牌加入手牌', min: 1, max: 1, selector: { player: 'controller', zone: 'cost' }, then: [moveCards(selected('cost'), 'hand')] })] })); } };
const BP01_007: CardBehavior = { cardNo: 'BP01-007', coverage: 'complete', onPlay(c) { c.enqueue(chooseCards({ bind: 'ally', prompt: '选择我方1张〈灰鸦小队〉角色PP+1500', min: 1, max: 1, selector: field('灰鸦小队'), then: [modifyStats(selected('ally'), { pp: 1500 }), chooseCards({ bind: 'discard', prompt: '可以丢弃任意数量手牌，每张再PP+1000', min: 0, max: 20, selector: { player: 'controller', zone: 'hand' }, then: [moveCards(selected('discard'), 'graveyard'), modifyStats(selected('ally'), { pp: 1000, perBinding: 'discard' })] })] })); } };
const BP01_008: CardBehavior = { cardNo: 'BP01-008', coverage: 'complete', auras(c) { return c.query.erosion('controller') >= 5 ? [{ selector: field('升格者'), pp: 1000 }] : []; }, oncePerTurnTriggers: ['onAttack'], onAttack(c) { c.enqueue(chooseCards({ bind: 'signals', prompt: '可以消除2张红色信号球', min: 0, max: 2, optionalExact: true, selector: { player: 'controller', zone: 'signal', feature: '信号球·红' }, then: [moveCards(selected('signals'), 'graveyard'), chooseCards({ bind: 'ascendant', prompt: '选择我方1张〈升格者〉角色', min: 1, max: 1, selector: field('升格者'), then: [modifyStats(selected('ascendant'), { pp: 2000 }, 'nextTurn'), grantKeywords(selected('ascendant'), ['充能 +1'], 'nextTurn')] })] })); } };
const BP01_009: CardBehavior = { cardNo: 'BP01-009', coverage: 'complete', continuous: () => ({ chargeSet: 0 }), onEnter(c) { if (c.query.erosion('controller') <= 3)
        c.enqueue(chooseOption('是否侵蚀+1并抽2张？', [{ id: 'yes', label: '侵蚀+1，抽2张', actions: [adjustErosion(1), draw(2)] }, { id: 'no', label: '不发动', actions: [] }])); } };
const BP01_010: CardBehavior = { cardNo: 'BP01-010', coverage: 'complete', onEnter(c) { c.enqueue(reorderSignalZone()); if (c.query.erosion('controller') >= 4)
        c.enqueue(chooseCards({ bind: 'pay', prompt: '可以消除2张同色信号球', min: 0, max: 2, optionalExact: true, selector: { player: 'controller', zone: 'signal' }, constraint: 'sameSignalColor', then: [moveCards(selected('pay'), 'graveyard'), chooseCards({ bind: 'luna', prompt: '选择《露娜·银冕》获得贯通', min: 1, max: 1, selector: { player: 'controller', zone: 'battlefield', name: '露娜·银冕' }, then: [grantKeywords(selected('luna'), ['贯通'])] })] })); } };
const BP01_011: CardBehavior = { cardNo: 'BP01-011', coverage: 'complete', onEnter(c) { if (c.query.erosionChangedThisTurn('controller'))
        c.enqueue(draw(1)); } };
const BP01_012: CardBehavior = { cardNo: 'BP01-012', coverage: 'complete', activated: [{ id: 'recover-signal', label: '横置并丢弃2张角色：回收墓地信号球', requiresReady: true, activate(c) { c.enqueue(setOrientation(source(), true), chooseCards({ bind: 'discard', prompt: '选择2张角色牌丢弃', min: 2, max: 2, selector: { player: 'controller', zone: 'hand', cardType: '角色牌' }, then: [moveCards(selected('discard'), 'graveyard'), chooseCards({ bind: 'signal', prompt: '选择墓地1张信号球放到信号球区最上方', min: 1, max: 1, selector: { player: 'controller', zone: 'graveyard', feature: '信号球' }, then: [moveCards(selected('signal'), 'signalTop')] })] })); } }] };
const BP01_013: CardBehavior = { cardNo: 'BP01-013', coverage: 'complete', requirements: { onPlay: [{ type: 'battlefieldName', player: 'controller', name: '露娜·银冕' }] }, onPlay(c) { if (c.query.erosion('controller') >= 5)
        c.enqueue(chooseCards({ bind: 'yellow', prompt: '可以消除2张黄色信号球使侵蚀-1', min: 0, max: 2, optionalExact: true, selector: { player: 'controller', zone: 'signal', feature: '信号球·黄' }, then: [moveCards(selected('yellow'), 'graveyard'), adjustErosion(-1)] })); } };
const BP01_014: CardBehavior = { cardNo: 'BP01-014', coverage: 'complete', continuous: () => ({ equipmentLimit: 2 }), activated: [{ id: 'great-blade', label: '消除2蓝：墓地大太刀装备并获得颜色替代', oncePerTurn: true, activate(c) { c.enqueue(chooseCards({ bind: 'blue', prompt: '选择2张蓝色信号球消除', min: 2, max: 2, selector: { player: 'controller', zone: 'signal', feature: '信号球·蓝' }, then: [moveCards(selected('blue'), 'graveyard'), chooseCards({ bind: 'blade', prompt: '选择墓地1张〈大太刀〉装备', min: 1, max: 1, selector: { player: 'controller', zone: 'graveyard', cardType: '装备牌', feature: '大太刀' }, then: [attachCards(selected('blade'), source(), 'equipment'), grantSignalAlias('蓝', ['红', '黄'])] })] })); } }], oncePerTurnTriggers: ['onAttack'], onAttack(c) { c.enqueue(chooseCards({ bind: 'yellow', prompt: '可以消除2张黄色信号球竖直并强化', min: 0, max: 2, optionalExact: true, selector: { player: 'controller', zone: 'signal', feature: '信号球·黄' }, then: [moveCards(selected('yellow'), 'graveyard'), setOrientation(source(), false), grantKeywords(source(), ['充能 +1']), modifyStats(source(), { pp: 1000 })] })); } };
const BP01_015: CardBehavior = { cardNo: 'BP01-015', coverage: 'complete' };
const BP01_016: CardBehavior = { cardNo: 'BP01-016', coverage: 'complete', continuous: () => ({ equipmentLimit: 2 }), activated: [{ id: 'sealed-blade', label: '消除1蓝：墓地封刃太刀装备', oncePerTurn: true, activate(c) { c.enqueue(chooseCards({ bind: 'blue', prompt: '选择1张蓝色信号球消除', min: 1, max: 1, selector: { player: 'controller', zone: 'signal', feature: '信号球·蓝' }, then: [moveCards(selected('blue'), 'graveyard'), chooseCards({ bind: 'blade', prompt: '选择墓地1张〈封刃太刀〉装备', min: 1, max: 1, selector: { player: 'controller', zone: 'graveyard', cardType: '装备牌', feature: '封刃太刀' }, then: [attachCards(selected('blade'), source(), 'equipment')] })] })); } }] };
const BP01_017: CardBehavior = { cardNo: 'BP01-017', coverage: 'complete', continuous: () => ({ equipmentLimit: 2 }), leaveReplacementEquipmentFeatures: ['小太刀', '大太刀'] };
const BP01_018: CardBehavior = { cardNo: 'BP01-018', coverage: 'complete', onEnter(c) { c.enqueue(chooseCards({ bind: 'discard', prompt: '丢弃1张手牌', min: 1, max: 1, selector: { player: 'controller', zone: 'hand' }, then: [moveCards(selected('discard'), 'graveyard'), when({ type: 'bindingMatches', binding: 'discard', selector: { cardType: '装备牌' } }, [draw(2)], [when({ type: 'bindingMatches', binding: 'discard', selector: { feature: '信号球' } }, [draw(2)], [draw(1)])])] })); } };
export const bp01_001_020: CardBehavior[] = [BP01_001, BP01_002, BP01_003, BP01_004, createVanilla('BP01-005'), createVanilla('BP01-006'), BP01_007, BP01_008, BP01_009, BP01_010, BP01_011, BP01_012, BP01_013, BP01_014, BP01_015, BP01_016, BP01_017, BP01_018, createVanilla('BP01-019'), createVanilla('BP01-020')];
