import { attachCards, chooseCards, chooseOption, dealDamage, grantKeywords, modifyStats, moveCards, preventCombatDamage, reorderSignalZone, revealTop, selected, setBaseStats, setOrientation, setSignalAliases, setSignalValue, shuffleDeck, source, } from '../../engine/actions';
import type { CardBehavior, CardContext } from '../../engine/card-behavior';
import { createChargeZero, createVanilla } from '../shared/vanilla';
const alphaField = { player: 'controller' as const, zone: 'battlefield' as const, feature: '阿尔法' };
const BP01_022: CardBehavior = { cardNo: 'BP01-022', coverage: 'complete', activated: [{ id: 'blue-alias', label: '使1张信号球本回合视为蓝色', oncePerTurn: true, activate(c) { if (!c.related || !c.query.matches(c.related, { feature: '阿尔法' }))
                return; c.enqueue(chooseCards({ bind: 'signal', prompt: '选择1张信号球本回合视为蓝色', min: 1, max: 1, physicalCards: true, selector: { player: 'controller', zone: 'signal' }, then: [setSignalAliases(selected('signal'), ['蓝'])] })); } }] };
const BP01_023: CardBehavior = { cardNo: 'BP01-023', coverage: 'complete', oncePerTurnTriggers: ['onAttack'], onAttack(c) { if (!c.related || !c.query.matches(c.related, { feature: '阿尔法' }))
        return; c.enqueue(chooseCards({ bind: 'tap', prompt: '可以横置我方战场1张牌，使本次攻击不能被PP5000以下角色阻挡', min: 0, max: 1, selector: { player: 'controller', zone: 'battlefield' }, then: [setOrientation(selected('tap'), true), grantKeywords(relatedTarget(), ['PP5000以下不能阻挡'])] })); } };
const relatedTarget = () => ({ type: 'related' as const });
const BP01_024: CardBehavior = { cardNo: 'BP01-024', coverage: 'complete', activated: [{ id: 'find-equipment', label: '横置并消除信号球：检索装备', requiresReady: true, activate(c) { c.enqueue(setOrientation(source(), true), chooseCards({ bind: 'signal', prompt: '选择1张任意信号球消除', min: 1, max: 1, selector: { player: 'controller', zone: 'signal' }, then: [moveCards(selected('signal'), 'graveyard'), revealTop(5, 'controller', 'top5'), chooseCards({ bind: 'equipment', prompt: '选择最多1张装备加入手牌', min: 0, max: 1, selector: { player: 'controller', zone: 'processing', cardType: '装备牌' }, poolBinding: 'top5', then: [moveCards(selected('equipment'), 'hand')], remainder: 'deckBottom', preserveSelectionOrder: true })] })); } }] };
const BP01_025: CardBehavior = { cardNo: 'BP01-025', coverage: 'complete', requirements: { onPlay: [{ type: 'battlefieldFeature', player: 'controller', feature: '阿尔法' }] }, onPlay(c) { c.enqueue(chooseCards({ bind: 'enemy', prompt: '选择对方1张角色能力无效且不能阻挡', min: 1, max: 1, selector: { player: 'opponent', zone: 'battlefield' }, then: [grantKeywords(selected('enemy'), ['能力无效', '不能阻挡']), chooseCards({ bind: 'red', prompt: '可以消除2张红色信号球竖直我方阿尔法', min: 0, max: 2, optionalExact: true, selector: { player: 'controller', zone: 'signal', feature: '信号球·红' }, then: [moveCards(selected('red'), 'graveyard'), chooseCards({ bind: 'alpha', prompt: '选择我方1张〈阿尔法〉竖直', min: 1, max: 1, selector: alphaField, then: [setOrientation(selected('alpha'), false)] })] })] })); } };
const BP01_026: CardBehavior = { cardNo: 'BP01-026', coverage: 'complete', onPlay(c) { c.enqueue(revealTop(7, 'controller', 'top7'), chooseCards({ bind: 'alpha', prompt: '选择最多1张〈阿尔法〉角色加入手牌', min: 0, max: 1, selector: { player: 'controller', zone: 'processing', cardType: '角色牌', feature: '阿尔法' }, poolBinding: 'top7', then: [moveCards(selected('alpha'), 'hand'), chooseCards({ bind: 'blade', prompt: '再选择最多1张〈封刃太刀〉加入手牌', min: 0, max: 1, selector: { player: 'controller', zone: 'processing', cardType: '装备牌', feature: '封刃太刀' }, poolBinding: 'top7', then: [moveCards(selected('blade'), 'hand')], remainder: 'deckBottom', preserveSelectionOrder: true })] })); } };
const BP01_027: CardBehavior = { cardNo: 'BP01-027', coverage: 'complete', requirements: { onPlay: [{ type: 'defendingPlayer' }] }, onPlay(c) { c.enqueue(chooseCards({ bind: 'equipment', prompt: '可以将我方1张装备放到墓地，使本次攻击不能造成伤害', min: 0, max: 1, selector: { player: 'controller', zone: 'equipment' }, then: [moveCards(selected('equipment'), 'graveyard'), preventCombatDamage()] })); } };
const BP01_028: CardBehavior = {
    cardNo: 'BP01-028', coverage: 'complete',
    onEnter(c) {
        c.enqueue(chooseCards({
            bind: 'return', prompt: '选择墓地/费用区最多6张《万世铭》加入牌组', min: 0, max: 6,
            selector: { player: 'controller', zone: 'graveyard', extraZones: ['cost'], name: '万世铭' },
            then: [
                moveCards(selected('return'), 'deckBottom'), shuffleDeck(),
                { type: 'chooseOption', prompt: '每加入2张选择1项（不可重复）', min: 0, max: 3, countFromBinding: { name: 'return', divisor: 2 }, options: [
                        { id: 'pp', label: '本回合充能+1且基本PP变为9999', actions: [setBaseStats(source(), { pp: 9999 }, 'turn'), grantKeywords(source(), ['充能 +1'])] },
                        { id: 'dp', label: '本回合DP+1', actions: [modifyStats(source(), { dp: 1 })] },
                        { id: 'ready', label: '本回合充能万世铭时竖直', actions: [grantKeywords(source(), ['万世铭再动'])] },
                    ] },
            ],
        }));
    },
    onAttackCharge(c) { if (c.related && c.query.hasKeyword(c.source, '万世铭再动') && c.query.matches(c.related, { feature: '万世铭' }))
        c.enqueue(setOrientation(source(), false)); },
};
const BP01_029: CardBehavior = { cardNo: 'BP01-029', coverage: 'complete', onEnter(c) { c.enqueue(chooseCards({ bind: 'discard', prompt: '丢弃1张手牌检索《万世铭》', min: 1, max: 1, selector: { player: 'controller', zone: 'hand' }, then: [moveCards(selected('discard'), 'graveyard'), chooseCards({ bind: 'search', prompt: '选择牌组1张《万世铭》加入手牌', min: 1, max: 1, selector: { player: 'controller', zone: 'deck', name: '万世铭' }, then: [moveCards(selected('search'), 'hand'), shuffleDeck()] })] })); }, oncePerTurnTriggers: ['onAttack', 'onBlock'], onAttack: recycleWanshiming, onBlock: recycleWanshiming };
function recycleWanshiming(c: CardContext) { c.enqueue(chooseCards({ bind: 'signals', prompt: '可以消除3张任意信号球', min: 0, max: 3, optionalExact: true, selector: { player: 'controller', zone: 'signal' }, then: [moveCards(selected('signals'), 'graveyard'), chooseCards({ bind: 'wanshi', prompt: '选择墓地最多2张《万世铭》', min: 0, max: 2, selector: { player: 'controller', zone: 'graveyard', name: '万世铭' }, then: [chooseCards({ bind: 'one', prompt: '选择其中1张加入手牌', min: 1, max: 1, selector: { player: 'controller', zone: 'graveyard', name: '万世铭' }, poolBinding: 'wanshi', then: [moveCards(selected('one'), 'hand'), chooseCards({ bind: 'cost', prompt: '将剩余选择的《万世铭》放到费用区', min: 0, max: 1, selector: { player: 'controller', zone: 'graveyard', name: '万世铭' }, poolBinding: 'wanshi', then: [moveCards(selected('cost'), 'costReady')] })] })] })] })); }
const BP01_030: CardBehavior = { cardNo: 'BP01-030', coverage: 'complete', onEnter(c) { c.enqueue(chooseCards({ bind: 'signals', prompt: '可以消除3张同色信号球', min: 0, max: 3, optionalExact: true, selector: { player: 'controller', zone: 'signal' }, constraint: 'sameSignalColor', then: [moveCards(selected('signals'), 'graveyard'), chooseCards({ bind: 'wanshi', prompt: '可以将费用区1张《万世铭》放到墓地', min: 0, max: 1, selector: { player: 'controller', zone: 'cost', name: '万世铭' }, then: [moveCards(selected('wanshi'), 'graveyard'), chooseCards({ bind: 'qu', prompt: '选择手牌费用5及以下〈曲〉角色出场', min: 1, max: 1, selector: { player: 'controller', zone: 'hand', feature: '曲', maxCost: 5 }, then: [moveCards(selected('qu'), 'battlefieldReady')] })] })] })); } };
const BP01_031: CardBehavior = { cardNo: 'BP01-031', coverage: 'complete', onEnter(c) { c.enqueue(revealTop(2, 'controller', 'top2'), chooseCards({ bind: 'chosen', prompt: '选择最多1张放到牌组顶或墓地', min: 0, max: 1, selector: { player: 'controller', zone: 'processing' }, poolBinding: 'top2', then: [chooseOption('选择放置位置', [{ id: 'top', label: '牌组顶', actions: [moveCards(selected('chosen'), 'deckTop')] }, { id: 'grave', label: '墓地', actions: [moveCards(selected('chosen'), 'graveyard')] }])], remainder: 'deckBottom', preserveSelectionOrder: true })); } };
const BP01_034: CardBehavior = { cardNo: 'BP01-034', coverage: 'complete', onEnter(c) { c.enqueue(chooseCards({ bind: 'discard', prompt: '丢弃1张手牌', min: 1, max: 1, selector: { player: 'controller', zone: 'hand' }, then: [moveCards(selected('discard'), 'graveyard'), revealTop(3, 'controller', 'top3'), chooseCards({ bind: 'qu', prompt: '选择1张〈曲〉角色加入手牌', min: 1, max: 1, selector: { player: 'controller', zone: 'processing', feature: '曲' }, poolBinding: 'top3', then: [moveCards(selected('qu'), 'hand')], remainder: 'deckBottom', preserveSelectionOrder: true })] })); } };
const BP01_035: CardBehavior = { cardNo: 'BP01-035', coverage: 'complete', activated: [{ id: 'discard-wanshi', label: '弃《万世铭》：充能+1或PP+2000', oncePerTurn: true, activate(c) { c.enqueue(chooseCards({ bind: 'discard', prompt: '丢弃手牌1张《万世铭》', min: 1, max: 1, selector: { player: 'controller', zone: 'hand', name: '万世铭' }, then: [moveCards(selected('discard'), 'graveyard'), chooseOption('选择强化', [{ id: 'charge', label: '充能+1', actions: [grantKeywords(source(), ['充能 +1'])] }, { id: 'pp', label: 'PP+2000', actions: [modifyStats(source(), { pp: 2000 })] }])] })); } }] };
const BP01_036: CardBehavior = { cardNo: 'BP01-036', coverage: 'complete', oncePerTurnTriggers: ['onAttack'], onAttack(c) { if (!c.related || !c.query.matches(c.related, { feature: '曲' }))
        return; c.enqueue(chooseCards({ bind: 'discard', prompt: '可以丢弃1张手牌查看牌组顶3张', min: 0, max: 1, selector: { player: 'controller', zone: 'hand' }, then: [moveCards(selected('discard'), 'graveyard'), revealTop(3, 'controller', 'top3'), chooseCards({ bind: 'chosen', prompt: '选择最多1张放到牌组顶或墓地', min: 0, max: 1, selector: { player: 'controller', zone: 'processing' }, poolBinding: 'top3', then: [chooseOption('选择放置位置', [{ id: 'top', label: '牌组顶', actions: [moveCards(selected('chosen'), 'deckTop')] }, { id: 'grave', label: '墓地', actions: [moveCards(selected('chosen'), 'graveyard')] }])], remainder: 'deckBottom', preserveSelectionOrder: true })] })); } };
const BP01_037: CardBehavior = { cardNo: 'BP01-037', coverage: 'complete', finalizeOnPlay: 'costTapped', processingReplacementFeature: '曲', requirements: { onPlay: [{ type: 'battlefieldFeature', player: 'controller', feature: '曲' }] }, onPlay(c) { c.enqueue(chooseCards({ bind: 'signal', prompt: '选择1张信号球，本回合视为3个同色信号球', min: 1, max: 1, physicalCards: true, selector: { player: 'controller', zone: 'signal' }, then: [setSignalValue(selected('signal'), 3)] })); } };
const BP01_038: CardBehavior = { cardNo: 'BP01-038', coverage: 'complete', finalizeOnPlay: 'costTapped', processingReplacementFeature: '曲', requirements: { onPlay: [{ type: 'battlefieldFeature', player: 'controller', feature: '曲' }] }, onPlay(c) { c.enqueue(chooseCards({ bind: 'signal', prompt: '选择墓地1张信号球', min: 1, max: 1, selector: { player: 'controller', zone: 'graveyard', feature: '信号球' }, then: [moveCards(selected('signal'), 'signalTop'), reorderSignalZone()] })); } };
const BP01_039: CardBehavior = { cardNo: 'BP01-039', coverage: 'complete', onPlay(c) { c.enqueue(chooseCards({ bind: 'enemy', prompt: '选择对方1张角色放到费用区（横置）', min: 1, max: 1, selector: { player: 'opponent', zone: 'battlefield' }, then: [moveCards(selected('enemy'), 'costTapped'), chooseCards({ bind: 'wanshi', prompt: '选择我方费用区1张《万世铭》竖直', min: 1, max: 1, selector: { player: 'controller', zone: 'cost', name: '万世铭' }, then: [setOrientation(selected('wanshi'), false)] })] })); } };
const BP01_040: CardBehavior = {
    cardNo: 'BP01-040', coverage: 'complete',
    continuous(c) { return { maxBlockerPp: c.query.underCount(c.source) >= 4 ? 5000 : undefined }; },
    auras(c) { return c.query.activePlayerId === c.source.playerId && c.query.underCount(c.source) >= 2 ? [{ selector: { player: 'controller', zone: 'battlefield', feature: '机械教会' }, pp: 1000 }] : []; },
    onEnter(c) { c.enqueue(chooseCards({ bind: 'pawa', prompt: '选择我方战场1张《帕瓦》放到该牌下方作为升变代价', min: 1, max: 1, selector: { player: 'controller', zone: 'battlefield', name: '帕瓦' }, then: [attachCards(selected('pawa'), source(), 'under')] })); },
    activated: [
        { id: 'recover-pawa', label: '弃1张手牌：墓地帕瓦放到该牌下方', oncePerTurn: true, activate(c) { c.enqueue(chooseCards({ bind: 'discard', prompt: '丢弃1张手牌', min: 1, max: 1, selector: { player: 'controller', zone: 'hand' }, then: [moveCards(selected('discard'), 'graveyard'), chooseCards({ bind: 'pawa', prompt: '选择墓地1张《帕瓦》放到该牌下方', min: 1, max: 1, selector: { player: 'controller', zone: 'graveyard', name: '帕瓦' }, then: [attachCards(selected('pawa'), source(), 'under')] })] })); } },
        { id: 'seven-pawa', label: '本局一次：2黄，对方受到1伤害', oncePerGame: true, activate(c) { if (c.query.underCount(c.source) < 7)
                return; c.enqueue(chooseCards({ bind: 'yellow', prompt: '选择2张黄色信号球消除', min: 2, max: 2, selector: { player: 'controller', zone: 'signal', feature: '信号球·黄' }, then: [moveCards(selected('yellow'), 'graveyard'), dealDamage(1)] })); } },
    ],
};
export const bp01_021_040: CardBehavior[] = [createVanilla('BP01-021'), BP01_022, BP01_023, BP01_024, BP01_025, BP01_026, BP01_027, BP01_028, BP01_029, BP01_030, BP01_031, createVanilla('BP01-032'), createChargeZero('BP01-033'), BP01_034, BP01_035, BP01_036, BP01_037, BP01_038, BP01_039, BP01_040];
