import { chooseCards, draw, grantKeywords, modifyStats, moveCards, preventCombatDamage, reorderSignalZone, revealTop, selected, setOrientation, shuffleDeck, source, when, } from '../../engine/actions';
import type { CardBehavior } from '../../engine/card-behavior';
import { createChargeZero, createVanilla } from '../shared/vanilla';
const dream = '梦赴光寥之乡';
const cerberus = { player: 'controller' as const, zone: 'battlefield' as const, feature: '三头犬小队' };
const BP01_061: CardBehavior = { cardNo: 'BP01-061', coverage: 'complete', onAttack(c) { if (!c.query.count({ player: 'controller', zone: 'graveyard', name: dream }))
        return; c.enqueue(revealTop(2, 'controller', 'top2'), chooseCards({ bind: 'top', prompt: '选择最多1张放回牌组顶', min: 0, max: 1, selector: { player: 'controller', zone: 'processing' }, poolBinding: 'top2', then: [moveCards(selected('top'), 'deckTop')], remainder: 'deckBottom', preserveSelectionOrder: true })); } };
const BP01_062: CardBehavior = { cardNo: 'BP01-062', coverage: 'complete', activated: [{ id: 'discard-boost', label: '弃1张手牌：获得对应强化', oncePerTurn: true, activate(c) { c.enqueue(chooseCards({ bind: 'discard', prompt: '丢弃1张手牌', min: 1, max: 1, selector: { player: 'controller', zone: 'hand' }, then: [moveCards(selected('discard'), 'graveyard'), when({ type: 'bindingMatches', binding: 'discard', selector: { name: dream } }, [grantKeywords(source(), ['突进']), modifyStats(source(), { pp: -1000 })], [modifyStats(source(), { pp: 1000 })])] })); } }] };
const BP01_065: CardBehavior = { cardNo: 'BP01-065', coverage: 'complete', requirements: { onPlay: [{ type: 'defendingPlayer' }] }, onPlay(c) { c.enqueue({ type: 'chooseOption', prompt: '是否将墓地2张《梦赴光寥之乡》洗回牌组并防止伤害？', min: 1, max: 1, options: [{ id: 'yes', label: '洗回2张并防止伤害', actions: [chooseCards({ bind: 'dreams', prompt: '选择墓地2张《梦赴光寥之乡》', min: 2, max: 2, selector: { player: 'controller', zone: 'graveyard', name: dream }, then: [moveCards(selected('dreams'), 'deckBottom'), shuffleDeck(), preventCombatDamage()] })] }, { id: 'no', label: '不发动', actions: [] }] }); } };
const BP01_066: CardBehavior = { cardNo: 'BP01-066', coverage: 'complete', onPlay(c) { c.enqueue({ type: 'chooseOption', prompt: '是否将墓地合计4张赛琳娜或梦赴光寥之乡洗回并抽2张？', min: 1, max: 1, options: [{ id: 'yes', label: '选择4张洗回并抽2张', actions: [chooseCards({ bind: 'cards', prompt: '选择合计4张《赛琳娜·希声》或《梦赴光寥之乡》', min: 4, max: 4, selector: { player: 'controller', zone: 'graveyard', names: ['赛琳娜·希声', dream] }, then: [moveCards(selected('cards'), 'deckBottom'), shuffleDeck(), draw(2)] })] }, { id: 'no', label: '不发动', actions: [] }] }); } };
const BP01_067: CardBehavior = { cardNo: 'BP01-067', coverage: 'complete', continuous(c) { return { cost: -Math.min(7, c.query.count({ player: 'controller', zone: 'hand', name: dream })) }; }, onPlay(c) { const count = Math.min(7, c.query.count({ player: 'controller', zone: 'hand', name: dream })); if (count)
        c.enqueue(chooseCards({ bind: 'dreams', prompt: `丢弃${count}张《梦赴光寥之乡》作为费用减免`, min: count, max: count, selector: { player: 'controller', zone: 'hand', name: dream }, then: [moveCards(selected('dreams'), 'graveyard')] })); c.enqueue(chooseCards({ bind: 'enemy', prompt: '选择对方1张角色放到牌组底', min: 1, max: 1, selector: { player: 'opponent', zone: 'battlefield' }, then: [moveCards(selected('enemy'), 'deckBottom')] })); } };
const BP01_068: CardBehavior = { cardNo: 'BP01-068', coverage: 'complete', onEnter(c) { c.enqueue(chooseCards({ bind: 'dream', prompt: '选择墓地1张《梦赴光寥之乡》加入手牌', min: 1, max: 1, selector: { player: 'controller', zone: 'graveyard', name: dream }, then: [moveCards(selected('dream'), 'hand')] })); } };
const BP01_069: CardBehavior = { cardNo: 'BP01-069', coverage: 'complete', continuous(c) { const ally = c.query.count({ player: 'controller', zone: 'battlefield', features: ['21号', '诺克提'] }) > 0; return { pp: ally ? 2000 : 0 }; }, onEnter(c) { c.enqueue(chooseCards({ bind: 'ally', prompt: '横置我方1张〈21号〉或〈诺克提〉角色以获得速攻', min: 1, max: 1, selector: { player: 'controller', zone: 'battlefield', features: ['21号', '诺克提'], tapped: false }, then: [setOrientation(selected('ally'), true), grantKeywords(source(), ['速攻'])] })); } };
const BP01_070: CardBehavior = { cardNo: 'BP01-070', coverage: 'complete', continuous(c) { return { ignoreAttribute: c.query.count({ player: 'controller', zone: 'battlefield', features: ['薇拉', '21号'] }) > 0 }; }, activated: [{ id: 'reorder-signals', label: '支付1费：重排信号球', oncePerTurn: true, requirements: [{ type: 'selectorCount', selector: cerberus, min: 3 }], activate(c) { c.enqueue(chooseCards({ bind: 'fee', prompt: '选择1张竖直费用支付', min: 1, max: 1, selector: { player: 'controller', zone: 'cost', tapped: false }, then: [{ type: 'payCards', target: selected('fee') }, reorderSignalZone()] })); } }] };
const BP01_071: CardBehavior = { cardNo: 'BP01-071', coverage: 'complete', requirements: { onPlay: [{ type: 'defendingPlayer' }, { type: 'selectorCount', selector: { ...cerberus, tapped: true }, min: 1 }] }, onPlay(c) { c.enqueue(preventCombatDamage()); } };
const BP01_073: CardBehavior = { cardNo: 'BP01-073', coverage: 'complete', oncePerTurnTriggers: ['onBlock', 'onOtherBlock'], triggerUsageGroup: { onBlock: 'block-boost', onOtherBlock: 'block-boost' }, onBlock(c) { c.enqueue(modifyStats(source(), { pp: 1000 })); }, onOtherBlock(c) { if (c.related)
        c.enqueue(modifyStats({ type: 'related' }, { pp: 1000 })); }, activated: [{ id: 'deploy-eagle', label: '消除2同色：突击鹰角色出场', oncePerTurn: true, activate(c) { c.enqueue(chooseCards({ bind: 'signals', prompt: '选择2张同色信号球消除', min: 2, max: 2, selector: { player: 'controller', zone: 'signal' }, constraint: 'sameSignalColor', then: [moveCards(selected('signals'), 'graveyard'), chooseCards({ bind: 'unit', prompt: '选择手牌费用不大于明费上限的〈突击鹰小队〉角色出场', min: 1, max: 1, selector: { player: 'controller', zone: 'hand', feature: '突击鹰小队', maxCost: c.query.costLimit('controller') }, then: [moveCards(selected('unit'), 'battlefieldReady'), grantKeywords(selected('unit'), ['不能攻击'])] })] })); } }] };
const BP01_075: CardBehavior = { cardNo: 'BP01-075', coverage: 'complete', onEnter(c) { c.enqueue(chooseCards({ bind: 'signals', prompt: '消除2张任意信号球', min: 2, max: 2, selector: { player: 'controller', zone: 'signal' }, then: [moveCards(selected('signals'), 'graveyard'), chooseCards({ bind: 'enemy', prompt: '选择对方费用3及以下角色横置', min: 1, max: 1, selector: { player: 'opponent', zone: 'battlefield', maxCost: 3 }, then: [setOrientation(selected('enemy'), true)] })] })); } };
const BP01_076: CardBehavior = { cardNo: 'BP01-076', coverage: 'complete', continuous(c) { return { chargeSet: 0, ignoreAttribute: c.query.count({ player: 'controller', zone: 'battlefield', feature: '突击鹰小队' }) > 1 }; }, activated: [{ id: 'return-eagle', label: '放到牌组底：回收墓地突击鹰角色', activate(c) { c.enqueue(moveCards(source(), 'deckBottom'), chooseCards({ bind: 'unit', prompt: '选择墓地1张〈突击鹰小队〉角色加入手牌', min: 1, max: 1, selector: { player: 'controller', zone: 'graveyard', feature: '突击鹰小队', cardType: '角色牌' }, then: [moveCards(selected('unit'), 'hand')] })); } }] };
export const bp01_061_077: CardBehavior[] = [BP01_061, BP01_062, createVanilla('BP01-063'), createVanilla('BP01-064'), BP01_065, BP01_066, BP01_067, BP01_068, BP01_069, BP01_070, BP01_071, createVanilla('BP01-072'), BP01_073, createChargeZero('BP01-074'), BP01_075, BP01_076, { cardNo: 'BP01-077', coverage: 'complete' }];
