import { computed, ref } from 'vue'
import { defineStore } from 'pinia'
import type { CardRecord, GameCard, GameLog, GamePhase, PlayerId, PlayerState } from '../types'
import type { CardBehavior, ContinuousContribution, GameQuery, ResolutionState } from '../game/engine/card-behavior'
import type { CardDestination } from '../game/engine/actions'
import type { CardReference, CardRequirement, CardSelector, CardTrigger, ChoiceOption, PendingChoice, RelativePlayer } from '../game/engine/model'
import { getCardBehavior } from '../game/cards'
import { SHIELD_COUNTER, shieldCounterBehavior } from '../game/engine/keyword-effects'

const makePlayer=(id:PlayerId,name:string):PlayerState=>({id,name,deck:[],hand:[],graveyard:[],costZone:[],signalZone:[],processingZone:[],battlefield:Array(5).fill(null),erosion:0,erosionChangedTurn:0,equipmentPlayedTurn:0,gloryShieldPlayedTurn:0,effects:[]})
const instance=(card:CardRecord):GameCard=>({instanceId:crypto.randomUUID(),card,tapped:false,faceDown:false,enteredTurn:0,abilityUses:{},scheduledMoves:[]})
function shuffle<T>(source:T[]){const result=[...source],random=new Uint32Array(1);for(let i=result.length-1;i>0;i--){crypto.getRandomValues(random);const j=random[0]!%(i+1);[result[i],result[j]]=[result[j]!,result[i]!]}return result}
function randomPlayer():PlayerId{const value=new Uint32Array(1);crypto.getRandomValues(value);return value[0]!%2===0?'player1':'player2'}

export const useGameStore=defineStore('game',()=>{
  const players=ref<[PlayerState,PlayerState]>([makePlayer('player1','玩家一'),makePlayer('player2','玩家二')])
  const activePlayer=ref<PlayerId>('player1'),firstPlayer=ref<PlayerId>('player1'),phase=ref<GamePhase>('竖直阶段'),turnNumber=ref(1),started=ref(false),gameStage=ref<'mulligan'|'playing'>('mulligan'),mulliganStep=ref(0),revealOpponentHand=ref(false),logs=ref<GameLog[]>([]),fillAvailable=ref(false),halted=ref(false)
  const pendingChoice=ref<PendingChoice|null>(null),resolution=ref<ResolutionState|null>(null)
  const chargeSequence=ref<{playerId:PlayerId;kind:'attack'|'damage';remaining:number;total:number;after?:'combatAttack'|'combatDamage'}|null>(null)
  const combat=ref<{attackerPlayerId:PlayerId;attackerSlot:number;targetPlayerId:PlayerId;targetSlot:number|null;blockerSlot:number|null;stage:'attackTriggers'|'attackCharge'|'response'|'block'|'blockTriggers'|'damageCharge';priorityPlayerId:PlayerId;passes:number;preventDamage:boolean}|null>(null)
  const endingTurn=ref(false)
  const triggerQueue:Array<{source:CardReference;card:GameCard;behavior:CardBehavior;trigger:CardTrigger;controllerId:PlayerId;related?:CardReference}>=[]
  const active=computed(()=>players.value.find(p=>p.id===activePlayer.value)!),opponent=computed(()=>players.value.find(p=>p.id!==activePlayer.value)!)
  const actingPlayerId=computed<PlayerId>(()=>combat.value?.stage==='response'?combat.value.priorityPlayerId:activePlayer.value)
  const actingPlayer=computed(()=>playerById(actingPlayerId.value))
  const pendingDiscard=computed(()=>gameStage.value==='playing'&&phase.value==='结束阶段'?Math.max(0,active.value.hand.length-7):0)
  const payableCosts=computed(()=>actingPlayer.value.costZone.filter(card=>!card.tapped))
  function log(text:string){logs.value.unshift({id:Date.now()+Math.random(),text,timestamp:new Date().toLocaleTimeString()})}
  const otherPlayerId=(id:PlayerId):PlayerId=>id==='player1'?'player2':'player1'
  const playerById=(id:PlayerId)=>players.value.find(player=>player.id===id)!
  const relativePlayer=(controllerId:PlayerId,relative:RelativePlayer)=>playerById(relative==='controller'?controllerId:otherPlayerId(controllerId))
  function makeQuery(controllerId:PlayerId):GameQuery{return{activePlayerId:activePlayer.value,turnNumber:turnNumber.value,erosion:(relative:RelativePlayer)=>relativePlayer(controllerId,relative).erosion,costLimit:(relative:RelativePlayer)=>relativePlayer(controllerId,relative).costZone.filter(card=>!card.faceDown).length,signalBottomCost:(relative:RelativePlayer)=>relativePlayer(controllerId,relative).signalZone.at(-1)?.card.cost??null,count:(selector:CardSelector)=>referencesFor(selector,controllerId).length,isTapped:(reference:CardReference)=>Boolean(cardAt(reference)?.tapped),matches:(reference:CardReference,selector:Omit<CardSelector,'player'|'zone'>)=>{const card=cardAt(reference);return Boolean(card&&cardMatches(card,{...selector,player:'controller',zone:reference.zone},reference.playerId,reference.slot))},hasEquipment:(reference:CardReference,cardNo:string)=>Boolean(playerById(reference.playerId).battlefield[reference.slot??-1]?.equipment.some(card=>card.card.card_no===cardNo)),underCount:(reference:CardReference,selector:Omit<CardSelector,'player'|'zone'>={})=>playerById(reference.playerId).battlefield[reference.slot??-1]?.underCards.filter(card=>cardMatches(card,{...selector,player:'controller',zone:'under'},reference.playerId)).length||0,erosionChangedThisTurn:(relative:RelativePlayer)=>relativePlayer(controllerId,relative).erosionChangedTurn===turnNumber.value,playedThisTurn:(relative:RelativePlayer,kind:'equipment'|'gloryShield')=>{const player=relativePlayer(controllerId,relative);return(kind==='equipment'?player.equipmentPlayedTurn:player.gloryShieldPlayedTurn)===turnNumber.value},hasKeyword:(reference:CardReference,keyword:string):boolean=>reference.zone==='battlefield'&&reference.slot!==undefined?currentKeywords(reference.playerId,reference.slot).includes(keyword):false,baseDp:(reference:CardReference)=>cardAt(reference)?.card.dp_value||0}}
  function continuousFor(card:GameCard,source:CardReference,controllerId:PlayerId):ContinuousContribution{const behavior=behaviorFor(card);if(!behavior?.continuous)return{};const actions:ResolutionState['actions']=[];return behavior.continuous({source,query:makeQuery(controllerId),enqueue(...next){actions.push(...next)}})}
  function auraFor(playerId:PlayerId,slot:number){
    const target=playerById(playerId).battlefield[slot];if(!target)return{}
    let pp=0,dp=0,chargeBonus=0;const keywords:string[]=[]
    for(const owner of players.value){owner.battlefield.forEach((field,sourceSlot)=>{if(!field)return
      const sources:Array<[GameCard,'battlefield'|'equipment']>=[[field.unit,'battlefield'],...field.equipment.map(item=>[item,'equipment'] as [GameCard,'equipment'])]
      for(const [card,zone] of sources){const behavior=behaviorFor(card);if(!behavior?.auras)continue;const source:CardReference={playerId:owner.id,zone,instanceId:card.instanceId,slot:sourceSlot}
        for(const aura of behavior.auras(makeCardContext(source,owner.id,[]))){if(aura.during==='controllerTurn'&&activePlayer.value!==owner.id)continue;if(aura.during==='opponentTurn'&&activePlayer.value===owner.id)continue;const expected=aura.selector.player==='any'?playerId:aura.selector.player==='controller'?owner.id:otherPlayerId(owner.id);if(expected!==playerId||!cardMatches(target.unit,aura.selector,playerId,slot))continue;pp+=aura.pp||0;dp+=aura.dp||0;chargeBonus+=aura.chargeBonus||0;keywords.push(...(aura.keywords||[]))}
      }
    });for(const effect of owner.effects){if(effect.kind!=='aura'||!effect.selector)continue;const expected=effect.selector.player==='any'?playerId:effect.selector.player==='controller'?owner.id:otherPlayerId(owner.id);if(expected!==playerId||!cardMatches(target.unit,effect.selector,playerId,slot))continue;pp+=effect.pp||0;dp+=effect.dp||0;chargeBonus+=effect.chargeBonus||0;keywords.push(...(effect.keywords||[]))}}
    return{pp,dp,chargeBonus,keywords}
  }
  function partnerFor(playerId:PlayerId,slot:number){const field=playerById(playerId).battlefield[slot],partner=field?.partner;if(!field||!partner)return{};const behavior=behaviorFor(partner);return behavior?.whilePartner?.(makeCardContext({playerId,zone:'partner',instanceId:partner.instanceId,slot},playerId,[],{playerId,zone:'battlefield',instanceId:field.unit.instanceId,slot}))||{}}
  function underFor(playerId:PlayerId,slot:number){const field=playerById(playerId).battlefield[slot];if(!field)return{};let pp=0,dp=0,chargeBonus=0;const keywords:string[]=[];for(let underIndex=0;underIndex<field.underCards.length;underIndex++){const card=field.underCards[underIndex]!,behavior=behaviorFor(card),value=behavior?.whileUnder?.(makeCardContext({playerId,zone:'under',instanceId:card.instanceId,slot,underIndex},playerId,[],{playerId,zone:'battlefield',instanceId:field.unit.instanceId,slot}))||{};pp+=value.pp||0;dp+=value.dp||0;chargeBonus+=value.chargeBonus||0;keywords.push(...(value.keywords||[]))}return{pp,dp,chargeBonus,keywords}}
  const actualPp=(value:number|null)=>value===null?0:value<100?value*1000:value
  function currentPp(playerId:PlayerId,slot:number){const field=playerById(playerId).battlefield[slot];if(!field)return 0;const continuous=continuousFor(field.unit,{playerId,zone:'battlefield',instanceId:field.unit.instanceId,slot},playerId),aura=auraFor(playerId,slot),partner=partnerFor(playerId,slot),under=underFor(playerId,slot),equipmentPp=field.equipment.reduce((sum,item)=>sum+actualPp(item.card.pp_value)+(continuousFor(item,{playerId,zone:'equipment',instanceId:item.instanceId,slot},playerId).pp||0),0),baseOverrideActive=field.basePpOverrideExpiresAtTurn===null||field.basePpOverrideExpiresAtTurn===turnNumber.value;return(baseOverrideActive&&field.basePpOverride!==undefined?field.basePpOverride:actualPp(field.unit.card.pp_value))+equipmentPp+(continuous.pp||0)+(aura.pp||0)+(partner.pp||0)+(under.pp||0)+field.modifiers.reduce((sum,item)=>sum+item.pp,0)}
  function currentDp(playerId:PlayerId,slot:number){const field=playerById(playerId).battlefield[slot];if(!field)return 0;const continuous=continuousFor(field.unit,{playerId,zone:'battlefield',instanceId:field.unit.instanceId,slot},playerId),aura=auraFor(playerId,slot),partner=partnerFor(playerId,slot),under=underFor(playerId,slot),baseOverrideActive=field.baseDpOverrideExpiresAtTurn===null||field.baseDpOverrideExpiresAtTurn===turnNumber.value;return(baseOverrideActive&&field.baseDpOverride!==undefined?field.baseDpOverride:(field.unit.card.dp_value??0))+(continuous.dp||0)+(aura.dp||0)+(partner.dp||0)+(under.dp||0)+field.modifiers.reduce((sum,item)=>sum+item.dp,0)}
  function currentKeywords(playerId:PlayerId,slot:number):string[]{const field=playerById(playerId).battlefield[slot];if(!field)return[];const continuous=continuousFor(field.unit,{playerId,zone:'battlefield',instanceId:field.unit.instanceId,slot},playerId),aura=auraFor(playerId,slot),partner=partnerFor(playerId,slot),under=underFor(playerId,slot);return[...(continuous.keywords||[]),...(aura.keywords||[]),...(partner.keywords||[]),...(under.keywords||[]),...field.modifiers.flatMap(item=>item.keywords)]}
  function currentCharge(playerId:PlayerId,slot:number){const field=playerById(playerId).battlefield[slot];if(!field)return 0;const continuous=continuousFor(field.unit,{playerId,zone:'battlefield',instanceId:field.unit.instanceId,slot},playerId),aura=auraFor(playerId,slot),partner=partnerFor(playerId,slot),under=underFor(playerId,slot),modifierBonus=currentKeywords(playerId,slot).reduce((sum,keyword)=>{const match=keyword.match(/充能\s*([+-]\d+)/);return sum+(match?Number(match[1]):0)},0);return Math.max(0,(continuous.chargeSet??1)+(continuous.chargeBonus||0)+(aura.chargeBonus||0)+(partner.chargeBonus||0)+(under.chargeBonus||0)+modifierBonus)}
  function fieldStats(playerId:PlayerId,slot:number){return{pp:currentPp(playerId,slot),dp:currentDp(playerId,slot)}}
  const isUpgradeCard=(card:GameCard)=>card.card.card_types.includes('升变角色牌')
  function upgradeTargets(card:GameCard,controllerId?:PlayerId){if(!isUpgradeCard(card))return[];const owner=playerById(controllerId||players.value.find(player=>player.hand.some(item=>item.instanceId===card.instanceId))?.id||activePlayer.value),effect=card.card.effect,costLimit=Number(effect.match(/费用上限(\d+)及以上/)?.[1]||0),targetCost=Number(effect.match(/费用(\d+)以下/)?.[1]||99),feature=effect.match(/费用\d+以下的<([^>]+)>/)?.[1],name=effect.match(/费用\d+以下的《([^》]+)》/)?.[1],grayRavenAlternative=card.card.card_no==='BP01-001'&&owner.graveyard.filter(item=>item.card.features.includes('灰鸦小队')).length>=10;if(owner.costZone.filter(item=>!item.faceDown).length<costLimit&&!grayRavenAlternative)return[];return owner.battlefield.flatMap((field,slot)=>field&&(field.unit.card.cost||0)<=targetCost&&(!feature||field.unit.card.features.includes(feature))&&(!name||field.unit.card.name===name)?[slot]:[])}
  function cardCost(card:GameCard,controllerId?:PlayerId){const ownerId=controllerId||players.value.find(player=>player.hand.some(item=>item.instanceId===card.instanceId))?.id||activePlayer.value,owner=playerById(ownerId),source:CardReference={playerId:ownerId,zone:'hand',instanceId:card.instanceId},continuous=continuousFor(card,source,ownerId),discount=owner.effects.filter(effect=>effect.kind==='nextCostDiscount'&&(!effect.feature||card.card.features.includes(effect.feature))&&(!effect.name||card.card.name.includes(effect.name))).reduce((sum,effect)=>sum+(effect.amount||0),0),firstEquipment=card.card.card_types.includes('装备牌')&&owner.equipmentPlayedTurn!==turnNumber.value&&owner.battlefield.some(field=>field?.unit.card.card_no==='BP01-015')?-1:0,gloryShield=card.card.name==='荣光护盾'&&owner.gloryShieldPlayedTurn!==turnNumber.value&&owner.battlefield.some(field=>field?.unit.card.card_no==='BP01-077')?1:null,base=isUpgradeCard(card)?Number(card.card.effect.match(/升变代价【(\d+)费】/)?.[1]||card.card.cost||0):(card.card.cost||0);return Math.max(0,gloryShield??base+(continuous.cost||0)+discount+firstEquipment)}
  function cardMatches(card:GameCard,selector:CardSelector,playerId:PlayerId,slot?:number){
    if(selector.excludeInstanceId===card.instanceId)return false
    if(selector.cardType&&!card.card.card_types.includes(selector.cardType))return false
    if(selector.feature&&!card.card.features.includes(selector.feature)){const wanted=selector.feature.match(/^信号球[·・](.)$/)?.[1],actual=card.card.signal_color||card.card.features.match(/信号球[·・](.)/)?.[1],aliases=[...(card.signalAliasesExpiresAtTurn===turnNumber.value?(card.signalAliases||[]):[]),...playerById(playerId).effects.filter(effect=>effect.kind==='signalAlias'&&effect.signalFrom===actual).flatMap(effect=>effect.signalTo||[])];if(!wanted||!aliases.includes(wanted))return false}
    if(selector.features&&!selector.features.some(feature=>card.card.features.includes(feature)))return false
    if(selector.name&&!card.card.name.includes(selector.name))return false
    if(selector.names&&!selector.names.some(name=>card.card.name.includes(name)))return false
    if(selector.cardNo&&card.card.card_no!==selector.cardNo)return false
    if(selector.attribute&&card.card.attribute!==selector.attribute)return false
    if(selector.minCost!==undefined&&(card.card.cost??0)<selector.minCost)return false
    if(selector.maxCost!==undefined&&(card.card.cost??0)>selector.maxCost)return false
    if(selector.tapped!==undefined&&card.tapped!==selector.tapped)return false
    if(selector.maxPp!==undefined&&(slot===undefined||currentPp(playerId,slot)>selector.maxPp))return false
    if(selector.cooperating!==undefined&&(slot===undefined||Boolean(playerById(playerId).battlefield[slot]?.partner)!==selector.cooperating))return false
    return true
  }
  function referencesFor(selector:CardSelector,controllerId:PlayerId,unfilteredDeckTop=false):ChoiceOption[]{
    if(selector.extraZones?.length)return [selector.zone,...selector.extraZones].flatMap(zone=>referencesFor({...selector,zone,extraZones:undefined},controllerId,unfilteredDeckTop))
    if(selector.player==='any')return[...referencesFor({...selector,player:'controller'},controllerId,unfilteredDeckTop),...referencesFor({...selector,player:'opponent'},controllerId,unfilteredDeckTop)]
    const player=relativePlayer(controllerId,selector.player),result:ChoiceOption[]=[]
    if(selector.zone==='battlefield')player.battlefield.forEach((field,slot)=>{if(field&&cardMatches(field.unit,selector,player.id,slot))result.push({ref:{playerId:player.id,zone:'battlefield',instanceId:field.unit.instanceId,slot},card:field.unit,label:`${player.name} · ${field.unit.card.name} · PP ${currentPp(player.id,slot)} / DP ${currentDp(player.id,slot)}`})})
    else if(selector.zone==='equipment')player.battlefield.forEach((field,slot)=>field?.equipment.forEach((card,attachmentIndex)=>{if(cardMatches(card,selector,player.id))result.push({ref:{playerId:player.id,zone:'equipment',instanceId:card.instanceId,slot,attachmentIndex},card,label:`${player.name} · ${card.card.name}（装备于${field.unit.card.name}）`})}))
    else if(selector.zone==='partner')player.battlefield.forEach((field,slot)=>{const card=field?.partner;if(card&&cardMatches(card,selector,player.id))result.push({ref:{playerId:player.id,zone:'partner',instanceId:card.instanceId,slot},card,label:`${player.name} · ${card.card.name}（协战搭档）`})})
    else if(selector.zone==='under')player.battlefield.forEach((field,slot)=>field?.underCards.forEach((card,underIndex)=>{if(cardMatches(card,selector,player.id))result.push({ref:{playerId:player.id,zone:'under',instanceId:card.instanceId,slot,underIndex},card,label:`${player.name} · ${card.card.name}（位于${field.unit.card.name}下方）`})}))
    else {
      const source=selector.zone==='deckTop'?player.deck.slice(0,selector.top||0):selector.zone==='deck'?player.deck:selector.zone==='hand'?player.hand:selector.zone==='graveyard'?player.graveyard:selector.zone==='processing'?player.processingZone:selector.zone==='cost'?player.costZone:player.signalZone
      source.forEach(card=>{if(unfilteredDeckTop||cardMatches(card,selector,player.id))result.push({ref:{playerId:player.id,zone:selector.zone,instanceId:card.instanceId},card,label:`${player.name} · ${card.card.name}`})})
    }
    return result
  }
  function conditionMet(condition:CardRequirement,controllerId:PlayerId){if(condition.type==='selectorCount')return referencesFor(condition.selector,controllerId).length>=condition.min;if(condition.type==='defendingPlayer')return combat.value?.targetPlayerId===controllerId;const player=relativePlayer(controllerId,condition.player);return player.battlefield.some(field=>field&&(condition.type==='battlefieldFeature'?field.unit.card.features.includes(condition.feature):field.unit.card.name.includes(condition.name)))}
  function behaviorFor(card:GameCard){return getCardBehavior(card.card.card_no)}
  function hasTrigger(behavior:CardBehavior,trigger:CardTrigger){return trigger==='onEnter'?Boolean(behavior.onEnter):trigger==='onAttack'?Boolean(behavior.onAttack):trigger==='onAttackCharge'?Boolean(behavior.onAttackCharge):trigger==='afterAttack'?Boolean(behavior.afterAttack):trigger==='onBlock'?Boolean(behavior.onBlock):trigger==='onOtherBlock'?Boolean(behavior.onOtherBlock):trigger==='onTurnEnd'?Boolean(behavior.onTurnEnd):trigger==='onOtherEnter'?Boolean(behavior.onOtherEnter):trigger==='onSignalConsumed'?Boolean(behavior.onSignalConsumed):trigger==='onPartnered'?Boolean(behavior.onPartnered):trigger==='onCharge'?Boolean(behavior.onCharge):Boolean(behavior.onPlay)}
  function triggerUsageKey(behavior:CardBehavior,trigger:CardTrigger){return`trigger:${behavior.triggerUsageGroup?.[trigger]||trigger}`}
  function queueTrigger(source:CardReference,card:GameCard,trigger:CardTrigger,controllerId:PlayerId,related?:CardReference){if(source.zone==='battlefield'&&playerById(source.playerId).battlefield[source.slot??-1]?.modifiers.some(item=>item.keywords.includes('能力无效')))return;const behavior=behaviorFor(card);if(!behavior||!hasTrigger(behavior,trigger))return;const key=triggerUsageKey(behavior,trigger);if(behavior.oncePerTurnTriggers?.includes(trigger)&&card.abilityUses[key]===turnNumber.value)return;const limit=behavior.triggerLimitPerTurn?.[trigger];if(limit){const turnKey=`${key}:turn`,countKey=`${key}:count`;if(card.abilityUses[turnKey]!==turnNumber.value){card.abilityUses[turnKey]=turnNumber.value;card.abilityUses[countKey]=0}if((card.abilityUses[countKey]||0)>=limit)return}triggerQueue.push({source,card,behavior,trigger,controllerId,related})}
  function queueHostTriggers(host:CardReference,trigger:'onAttack'|'onAttackCharge'|'afterAttack'|'onBlock',related?:CardReference){const field=playerById(host.playerId).battlefield[host.slot??-1];if(!field)return;queueTrigger(host,field.unit,trigger,host.playerId,related);field.equipment.forEach((card,attachmentIndex)=>queueTrigger({playerId:host.playerId,zone:'equipment',instanceId:card.instanceId,slot:host.slot,attachmentIndex},card,trigger,host.playerId,host));if(field.partner)queueTrigger({playerId:host.playerId,zone:'partner',instanceId:field.partner.instanceId,slot:host.slot},field.partner,trigger,host.playerId,host);if(trigger==='onBlock')playerById(host.playerId).battlefield.forEach((other,slot)=>{if(other&&slot!==host.slot)queueTrigger({playerId:host.playerId,zone:'battlefield',instanceId:other.unit.instanceId,slot},other.unit,'onOtherBlock',host.playerId,host)})}
  function queueOtherEnterTriggers(entered:CardReference){for(const player of players.value)player.battlefield.forEach((field,slot)=>{if(!field)return;const source={playerId:player.id,zone:'battlefield' as const,instanceId:field.unit.instanceId,slot};if(source.instanceId!==entered.instanceId)queueTrigger(source,field.unit,'onOtherEnter',player.id,entered)})}
  function queueSignalConsumedTriggers(playerId:PlayerId){const player=playerById(playerId);for(const card of player.graveyard)queueTrigger({playerId,zone:'graveyard',instanceId:card.instanceId},card,'onSignalConsumed',playerId)}
  function drainTriggerQueue(){if(resolution.value||pendingChoice.value)return;const next=triggerQueue.shift();if(next)beginResolution(next.source,next.card,next.behavior,next.trigger,'none',next.controllerId,next.related)}
  function makeCardContext(source:CardReference,controllerId:PlayerId,actions:ResolutionState['actions'],related?:CardReference){return{source,related,query:makeQuery(controllerId),enqueue(...next:ResolutionState['actions']){actions.push(...next)}}}
  function actionsFrom(behavior:CardBehavior,trigger:CardTrigger,source:CardReference,controllerId=activePlayer.value,related?:CardReference){const actions:ResolutionState['actions']=[],context=makeCardContext(source,controllerId,actions,related);if(trigger==='onPlay')behavior.onPlay?.(context);else if(trigger==='onEnter')behavior.onEnter?.(context);else if(trigger==='onCharge')behavior.onCharge?.(context);else if(trigger==='onPartnered')behavior.onPartnered?.(context);else if(trigger==='onAttack')behavior.onAttack?.(context);else if(trigger==='onAttackCharge')behavior.onAttackCharge?.(context);else if(trigger==='afterAttack')behavior.afterAttack?.(context);else if(trigger==='onBlock')behavior.onBlock?.(context);else if(trigger==='onOtherBlock')behavior.onOtherBlock?.(context);else if(trigger==='onTurnEnd')behavior.onTurnEnd?.(context);else if(trigger==='onOtherEnter')behavior.onOtherEnter?.(context);else if(trigger==='onSignalConsumed')behavior.onSignalConsumed?.(context);return actions}
  function behaviorReasons(behavior:CardBehavior|undefined,trigger:CardTrigger,_source:CardReference,controllerId:PlayerId){if(!behavior)return[];const reasons:string[]=[];for(const condition of behavior.requirements?.[trigger]||[]){if(!conditionMet(condition,controllerId))reasons.push(condition.type==='defendingPlayer'?'只能在我方玩家被攻击时使用':condition.type==='selectorCount'?`满足条件的卡牌少于${condition.min}张`:condition.type==='battlefieldFeature'?`战场不存在具有〈${condition.feature}〉特征的角色`:`战场不存在《${condition.name}》`)}return reasons}
  function cardAt(reference:CardReference){const player=playerById(reference.playerId);if(reference.zone==='battlefield')return player.battlefield[reference.slot??-1]?.unit;if(reference.zone==='equipment')return player.battlefield[reference.slot??-1]?.equipment.find(card=>card.instanceId===reference.instanceId);if(reference.zone==='partner')return player.battlefield[reference.slot??-1]?.partner||undefined;if(reference.zone==='under')return player.battlefield[reference.slot??-1]?.underCards.find(card=>card.instanceId===reference.instanceId);const zone=reference.zone==='hand'?player.hand:reference.zone==='graveyard'?player.graveyard:reference.zone==='processing'?player.processingZone:reference.zone==='cost'?player.costZone:reference.zone==='signal'?player.signalZone:player.deck;return zone.find(card=>card.instanceId===reference.instanceId)}
  function replaceLeaving(field:NonNullable<PlayerState['battlefield'][number]>,player:PlayerState){const features=behaviorFor(field.unit)?.leaveReplacementEquipmentFeatures;if(!features?.length||!features.every(feature=>field.equipment.some(card=>card.card.features.includes(feature))))return false;for(const feature of features){const index=field.equipment.findIndex(card=>card.card.features.includes(feature));if(index>=0)player.graveyard.unshift(...field.equipment.splice(index,1))}log(`《${field.unit.card.name}》将指定装备放入墓地，代替离场`);return true}
  function detach(reference:CardReference){const player=playerById(reference.playerId);if(reference.zone==='battlefield'){const slot=reference.slot??-1,field=player.battlefield[slot];if(!field||field.unit.instanceId!==reference.instanceId)return null;if(replaceLeaving(field,player))return null;player.battlefield[slot]=null;player.graveyard.unshift(...field.underCards,...field.equipment,...(field.partner?[field.partner]:[]));return field.unit}if(reference.zone==='equipment'){const field=player.battlefield[reference.slot??-1];if(!field)return null;const index=field.equipment.findIndex(card=>card.instanceId===reference.instanceId);return index<0?null:field.equipment.splice(index,1)[0]||null}if(reference.zone==='partner'){const field=player.battlefield[reference.slot??-1];if(!field||field.partner?.instanceId!==reference.instanceId)return null;const card=field.partner;field.partner=null;return card}if(reference.zone==='under'){const field=player.battlefield[reference.slot??-1];if(!field)return null;const index=field.underCards.findIndex(card=>card.instanceId===reference.instanceId);return index<0?null:field.underCards.splice(index,1)[0]||null}const zone=reference.zone==='hand'?player.hand:reference.zone==='graveyard'?player.graveyard:reference.zone==='processing'?player.processingZone:reference.zone==='cost'?player.costZone:reference.zone==='signal'?player.signalZone:player.deck,index=zone.findIndex(card=>card.instanceId===reference.instanceId);if(index<0)return null;return zone.splice(index,1)[0]||null}
  function moveReferences(references:CardReference[],destination:import('../game/engine/actions').CardDestination){
    const labels:Record<typeof destination,string>={hand:'手牌',graveyard:'墓地',signalTop:'信号球区最上方',signalBottom:'信号球区最下方',deckTop:'牌组顶',deckBottom:'牌组底',costReady:'费用区（竖直）',costTapped:'费用区（横置）',costFaceDown:'费用区（里侧竖直）',battlefieldReady:'战场（竖直）',battlefieldTapped:'战场（横置）'}
    const consumedBy=new Set<PlayerId>();for(const reference of references){const wasSignal=reference.zone==='signal'&&destination==='graveyard',card=detach(reference);if(!card)continue;const player=playerById(reference.playerId);if(destination==='hand')player.hand.push(card);else if(destination==='graveyard')player.graveyard.unshift(card);else if(destination==='signalTop')player.signalZone.unshift(card);else if(destination==='signalBottom')player.signalZone.push(card);else if(destination==='deckTop')player.deck.unshift(card);else if(destination==='deckBottom')player.deck.push(card);else if(destination==='costReady'||destination==='costTapped'||destination==='costFaceDown'){card.tapped=destination==='costTapped';card.faceDown=destination==='costFaceDown';player.costZone.push(card)}else{const slot=player.battlefield.findIndex(field=>field===null);if(slot<0){player.graveyard.unshift(card);log(`战场没有空位，《${card.card.name}》改为进入墓地`);continue}card.tapped=destination==='battlefieldTapped';card.enteredTurn=turnNumber.value;player.battlefield[slot]={unit:card,underCards:[],equipment:[],partner:null,modifiers:[]};const entered={playerId:player.id,zone:'battlefield' as const,instanceId:card.instanceId,slot};queueTrigger(entered,card,'onEnter',player.id);queueOtherEnterTriggers(entered)}if(wasSignal)consumedBy.add(reference.playerId);log(`《${card.card.name}》移动至${labels[destination]}`)}for(const playerId of consumedBy)queueSignalConsumedTriggers(playerId)
    drainTriggerQueue()
  }
  function destroyReferences(references:CardReference[]){for(const reference of references){if(reference.zone!=='battlefield')continue;const player=playerById(reference.playerId),slot=reference.slot??-1,field=player.battlefield[slot];if(!field||replaceLeaving(field,player))continue;player.battlefield[slot]=null;player.graveyard.unshift(...field.underCards,...field.equipment,...(field.partner?[field.partner]:[]),field.unit);log(`《${field.unit.card.name}》被破坏并进入墓地`)}}
  function resolveRemainder(references:CardReference[],mode:'deckBottom'|'graveyard'|'shuffle'){if(!references.length)return;const playerId=references[0]!.playerId;moveReferences(references,mode==='graveyard'?'graveyard':'deckBottom');if(mode==='shuffle'){const player=playerById(playerId);player.deck=shuffle(player.deck);log(`${player.name}将剩余公开牌加入牌组并洗切`)}}
  function continueSystemFlow(){if(resolution.value||pendingChoice.value)return;if(triggerQueue.length){drainTriggerQueue();return}if(chargeSequence.value){continueCharge();return}const state=combat.value;if(state?.stage==='attackTriggers'){state.stage='attackCharge';startCharge(state.attackerPlayerId,currentCharge(state.attackerPlayerId,state.attackerSlot),'attack','combatAttack');return}if(state?.stage==='blockTriggers'){resolveCombat();return}if(endingTurn.value)completeTurn()}
  function finishResolution(){const state=resolution.value;if(!state)return;if(state.finalize!=='none'){const source=state.source,card=cardAt(source);if(card)moveReferences([source],state.finalize)}log(`《${state.sourceName}》的当前效果结算完成`);resolution.value=null;pendingChoice.value=null;continueSystemFlow()}
  function markTriggerUsed(state:ResolutionState){if(!state.trigger)return;const card=cardAt(state.source),behavior=card?behaviorFor(card):undefined;if(!card||!behavior)return;const key=triggerUsageKey(behavior,state.trigger);if(behavior.oncePerTurnTriggers?.includes(state.trigger))card.abilityUses[key]=turnNumber.value;const limit=behavior.triggerLimitPerTurn?.[state.trigger];if(limit){const turnKey=`${key}:turn`,countKey=`${key}:count`;if(card.abilityUses[turnKey]!==turnNumber.value){card.abilityUses[turnKey]=turnNumber.value;card.abilityUses[countKey]=0}card.abilityUses[countKey]=(card.abilityUses[countKey]||0)+1}}
  function isOptionalEnterCost(state:ResolutionState,action:Extract<ResolutionState['actions'][number],{type:'chooseCards'}>){if(state.trigger!=='onEnter'||action.min===0)return false;const first=action.then[0];if(!first)return false;const bound=(target:{type:string;name?:string})=>target.type==='binding'&&target.name===action.bind;return first.type==='moveCards'&&bound(first.target)&&first.destination==='graveyard'||first.type==='payCards'&&bound(first.target)||first.type==='setOrientation'&&bound(first.target)&&first.tapped}
  function runResolution(){
    const state=resolution.value;if(!state||pendingChoice.value)return
    while(state.cursor<state.actions.length){const action=state.actions[state.cursor]!
      if(action.type==='draw'){draw(relativePlayer(state.controllerId,action.player),action.amount);state.cursor++;continue}
      if(action.type==='chooseCards'){
        const boundPool=action.poolBinding?(state.bindings[action.poolBinding]||[]):null
        const pool=boundPool?boundPool.map(ref=>{const card=cardAt(ref);return card?{ref,card,label:`${playerById(ref.playerId).name} · ${card.card.name}`}:null}).filter(Boolean) as ChoiceOption[]:action.selector.zone==='deckTop'?referencesFor(action.selector,state.controllerId,true):referencesFor(action.selector,state.controllerId)
        const options=boundPool?pool.filter(option=>cardMatches(option.card,action.selector,option.ref.playerId,option.ref.slot)):referencesFor(action.selector,state.controllerId)
        state.bindings[`${action.bind}__pool`]=pool.map(option=>option.ref)
        if(options.length<action.min){log(`“${action.prompt}”没有合法对象，该部分效果不执行`);if(action.remainder)resolveRemainder(pool.map(option=>option.ref),action.remainder);state.cursor++;continue}
        const signalWeighted=action.selector.zone==='signal'&&!action.physicalCards&&!action.preserveSelectionOrder,optionalCost=isOptionalEnterCost(state,action);pendingChoice.value={kind:'cards',id:Date.now()+Math.random(),prompt:action.prompt,min:optionalCost?0:signalWeighted&&action.min>0?1:action.min,max:Math.min(action.max,options.length),options};return
      }
      if(action.type==='chooseOption'){const derived=action.countFromBinding?Math.floor((state.bindings[action.countFromBinding.name]||[]).length/(action.countFromBinding.divisor||1)):null,min=derived??action.min,max=derived??action.max;if(max===0){state.cursor++;continue}pendingChoice.value={kind:'options',id:Date.now()+Math.random(),prompt:action.prompt,min:Math.min(min,action.options.length),max:Math.min(max,action.options.length),options:action.options.map(option=>({id:option.id,label:option.label}))};return}
      if(action.type==='adjustErosion'){const player=relativePlayer(state.controllerId,action.player),before=player.erosion;player.erosion=Math.max(0,Math.min(7,player.erosion+action.amount));if(player.erosion!==before)player.erosionChangedTurn=turnNumber.value;log(`${player.name}的侵蚀计数由${before}变为${player.erosion}`);state.cursor++;continue}
      if(action.type==='mill'){const player=relativePlayer(state.controllerId,action.player),cards=player.deck.splice(0,action.amount);player.graveyard.unshift(...cards);if(action.bind)state.bindings[action.bind]=cards.map(card=>({playerId:player.id,zone:'graveyard',instanceId:card.instanceId}));log(`${player.name}将牌组顶${cards.length}张牌放置到墓地`);state.cursor++;continue}
      if(action.type==='revealTop'){const player=relativePlayer(state.controllerId,action.player),cards=player.deck.splice(0,action.amount),cause=cardAt(state.source),relatedCause=state.related?cardAt(state.related):undefined,quCause=Boolean(cause?.card.features.includes('曲')||relatedCause?.card.features.includes('曲')),revealed:GameCard[]=[];for(const card of cards){const behavior=behaviorFor(card);if(quCause&&behavior?.processingReplacementFeature==='曲'){card.tapped=true;card.faceDown=false;player.costZone.push(card);log(`《${card.card.name}》因〈曲〉角色的效果改为横置放入费用区`)}else{player.processingZone.push(card);revealed.push(card)}}if(action.bind)state.bindings[action.bind]=revealed.map(card=>({playerId:player.id,zone:'processing',instanceId:card.instanceId}));log(`${player.name}公开牌组顶${cards.length}张牌至处理区`);state.cursor++;continue}
      if(action.type==='shuffle'){const player=relativePlayer(state.controllerId,action.player);player.deck=shuffle(player.deck);log(`${player.name}洗切牌组`);state.cursor++;continue}
      if(action.type==='grantNextCostDiscount'){const player=relativePlayer(state.controllerId,action.player);player.effects.push({id:crypto.randomUUID(),kind:'nextCostDiscount',amount:action.amount,feature:action.feature,name:action.name,expiresAtTurn:turnNumber.value});log(`${player.name}使用的下一张指定角色费用${action.amount}`);state.cursor++;continue}
      if(action.type==='grantAura'){const player=relativePlayer(state.controllerId,action.player);player.effects.push({id:crypto.randomUUID(),kind:'aura',selector:action.selector,pp:action.pp,dp:action.dp,chargeBonus:action.chargeBonus,keywords:action.keywords,expiresAtTurn:turnNumber.value+(action.duration==='nextTurn'?1:0)});log(`${player.name}获得临时战场持续效果`);state.cursor++;continue}
      if(action.type==='conditional'){let matched=false;if(action.condition.type==='bindingMatches'){const selector=action.condition.selector;matched=(state.bindings[action.condition.binding]||[]).some(reference=>{const card=cardAt(reference);return Boolean(card&&cardMatches(card,{...selector,player:'controller',zone:reference.zone},reference.playerId,reference.slot))})}else if(action.condition.type==='count'){const count=referencesFor(action.condition.selector,state.controllerId).length;matched=(action.condition.min===undefined||count>=action.condition.min)&&(action.condition.max===undefined||count<=action.condition.max)}else if(action.condition.type==='erosion'){const value=relativePlayer(state.controllerId,action.condition.player).erosion;matched=(action.condition.min===undefined||value>=action.condition.min)&&(action.condition.max===undefined||value<=action.condition.max)}else{const player=relativePlayer(state.controllerId,action.condition.player),other=playerById(otherPlayerId(player.id));matched=player.erosion>=other.erosion}state.actions.splice(state.cursor,1,...(matched?action.then:(action.otherwise||[])));continue}
      if(action.type==='formCooperation'){const partnerRefs=action.partner.type==='source'?[state.source]:action.partner.type==='related'?(state.related?[state.related]:[]):(state.bindings[action.partner.name]||[]),host=state.source,field=host.zone==='battlefield'?playerById(host.playerId).battlefield[host.slot??-1]:null,partnerRef=partnerRefs[0];if(field&&partnerRef&&!field.partner){const partner=detach(partnerRef);if(partner){field.partner=partner;field.partnerFromZone=partnerRef.zone==='battlefield'?'battlefield':partnerRef.zone==='graveyard'?'graveyard':'hand';field.partnerOriginalSlot=partnerRef.slot;field.partnerFormedTurn=turnNumber.value;log(`《${partner.card.name}》成为《${field.unit.card.name}》的协战搭档`);const behavior=behaviorFor(partner);if(behavior?.onPartnered)triggerQueue.push({source:{playerId:host.playerId,zone:'partner',instanceId:partner.instanceId,slot:host.slot},card:partner,behavior,trigger:'onPartnered',controllerId:host.playerId,related:host})}}state.cursor++;continue}
      if(action.type==='preventCombatDamage'){if(combat.value)combat.value.preventDamage=true;log('本次攻击不能造成伤害');state.cursor++;continue}
      if(action.type==='dealDamage'){const player=relativePlayer(state.controllerId,action.player);if(!chargeSequence.value)chargeSequence.value={playerId:player.id,kind:'damage',remaining:action.amount,total:action.amount};state.cursor++;continue}
      if(action.type==='grantSignalAlias'){const player=relativePlayer(state.controllerId,action.player);player.effects.push({id:crypto.randomUUID(),kind:'signalAlias',signalFrom:action.from,signalTo:action.to,expiresAtTurn:turnNumber.value});log(`${player.name}的${action.from}色信号球本回合也可视为${action.to.join('或')}色`);state.cursor++;continue}
      if(action.type==='reorderSignalZone'){const player=relativePlayer(state.controllerId,action.player),count=player.signalZone.length;if(!count){state.cursor++;continue}state.actions.splice(state.cursor,1,{type:'chooseCards',bind:`signalOrder:${state.cursor}`,prompt:'按希望从最上方到最下方的顺序依次选择全部信号球',min:count,max:count,physicalCards:true,preserveSelectionOrder:true,selector:{player:action.player,zone:'signal'},then:[{type:'moveCards',target:{type:'binding',name:`signalOrder:${state.cursor}`},destination:'signalBottom'}]});continue}
      if(action.type==='performUpgrade'){const refs=(target:{type:'source'}|{type:'related'}|{type:'binding';name:string})=>target.type==='source'?[state.source]:target.type==='related'?(state.related?[state.related]:[]):(state.bindings[target.name]||[]),upgradeRef=refs(action.upgrade)[0],hostRef=refs(action.host)[0],underRefs=action.under?refs(action.under):[],hostField=hostRef?.zone==='battlefield'?playerById(hostRef.playerId).battlefield[hostRef.slot??-1]:null,upgrade=upgradeRef?detach(upgradeRef):null;if(hostField&&upgrade){hostField.underCards.push(hostField.unit);for(const ref of underRefs){const card=detach(ref);if(card)hostField.underCards.push(card)}hostField.unit=upgrade;upgrade.enteredTurn=turnNumber.value;upgrade.tapped=false;hostField.modifiers.push({id:crypto.randomUUID(),pp:0,dp:0,keywords:['速攻'],expiresAtTurn:turnNumber.value,sourceCardNo:upgrade.card.card_no});const entered={playerId:hostRef!.playerId,zone:'battlefield' as const,instanceId:upgrade.instanceId,slot:hostRef!.slot};queueTrigger(entered,upgrade,'onEnter',hostRef!.playerId);queueOtherEnterTriggers(entered);log(`《${upgrade.card.name}》无视升变条件与代价升变出场`)}state.cursor++;continue}
      if(action.type==='attachCards'){const cardRefs=action.cards.type==='source'?[state.source]:action.cards.type==='related'?(state.related?[state.related]:[]):(state.bindings[action.cards.name]||[]),hostRefs=action.host.type==='source'?[state.source]:action.host.type==='related'?(state.related?[state.related]:[]):(state.bindings[action.host.name]||[]),host=hostRefs[0],field=host?.zone==='battlefield'?playerById(host.playerId).battlefield[host.slot??-1]:null;if(field)for(const ref of cardRefs){if(ref.instanceId===field.unit.instanceId)continue;const card=detach(ref);if(!card)continue;if(action.kind==='under')field.underCards.push(card);else field.equipment.push(card);log(`《${card.card.name}》放置到《${field.unit.card.name}》${action.kind==='under'?'下方':'的装备区'}`)}state.cursor++;continue}
      const targets=action.target.type==='source'?[state.source]:action.target.type==='related'?(state.related?[state.related]:[]):(state.bindings[action.target.name]||[])
      if(action.type==='moveCards')moveReferences(targets,action.destination)
      else if(action.type==='payCards'){for(const target of targets){const card=cardAt(target);if(!card)continue;if(card.faceDown)moveReferences([target],'graveyard');else card.tapped=true}log(`支付${targets.length}张费用`)}
      else if(action.type==='scheduleMove'){for(const target of targets){const card=cardAt(target);if(card)card.scheduledMoves.push({destination:action.destination,executeTurn:turnNumber.value+(action.at==='nextTurnEnd'?1:0)})}}
      else if(action.type==='destroyCards')destroyReferences(targets)
      else if(action.type==='setOrientation'){for(const target of targets){const card=cardAt(target);if(card)card.tapped=action.tapped}log(`选择的卡牌变为${action.tapped?'横置':'竖直'}状态`)}
      else if(action.type==='setSignalValue'){for(const target of targets){const card=cardAt(target);if(card){card.signalValue=action.value;card.signalValueExpiresAtTurn=turnNumber.value}}log(`选择的信号球本回合视为${action.value}个同色信号球`)}
      else if(action.type==='setSignalAliases'){for(const target of targets){const card=cardAt(target);if(card){card.signalAliases=action.colors;card.signalAliasesExpiresAtTurn=turnNumber.value}}log(`选择的信号球本回合也可视为${action.colors.join('或')}色`)}
      else if(action.type==='setBaseStats'){for(const target of targets){if(target.zone!=='battlefield')continue;const field=playerById(target.playerId).battlefield[target.slot??-1];if(!field)continue;const expires=action.duration==='permanent'?null:turnNumber.value;if(action.pp!==undefined){field.basePpOverride=action.pp;field.basePpOverrideExpiresAtTurn=expires}if(action.dp!==undefined){field.baseDpOverride=action.dp;field.baseDpOverrideExpiresAtTurn=expires}}log('选择角色的基本数值已变更')}
      else if(action.type==='modifyStats'){const scale=action.perBinding?(state.bindings[action.perBinding]||[]).length:1;for(const target of targets){if(target.zone!=='battlefield')continue;const field=playerById(target.playerId).battlefield[target.slot??-1];if(!field)continue;field.modifiers.push({id:crypto.randomUUID(),pp:(action.pp||0)*scale,dp:(action.dp||0)*scale,keywords:[],expiresAtTurn:action.duration==='permanent'?null:turnNumber.value+(action.duration==='nextTurn'?1:0),sourceCardNo:state.sourceCardNo});log(`《${field.unit.card.name}》${action.duration==='permanent'?'永久':action.duration==='nextTurn'?'直到下个回合结束':'本回合'}${action.pp?`PP${action.pp*scale>0?'+':''}${action.pp*scale}`:''}${action.pp&&action.dp?'、':''}${action.dp?`DP${action.dp*scale>0?'+':''}${action.dp*scale}`:''}`)}const defeated=targets.filter(target=>target.zone==='battlefield'&&Boolean(playerById(target.playerId).battlefield[target.slot??-1])&&currentPp(target.playerId,target.slot??-1)<=0);if(defeated.length)destroyReferences(defeated)}
      else if(action.type==='grantKeywords'){for(const target of targets){if(target.zone!=='battlefield')continue;const field=playerById(target.playerId).battlefield[target.slot??-1];if(!field)continue;field.modifiers.push({id:crypto.randomUUID(),pp:0,dp:0,keywords:action.keywords,expiresAtTurn:action.duration==='permanent'?null:turnNumber.value+(action.duration==='nextTurn'?1:0),sourceCardNo:state.sourceCardNo});log(`《${field.unit.card.name}》获得【${action.keywords.join('】【')}】`)}}
      state.cursor++
    }
    finishResolution()
  }
  function beginResolution(source:CardReference,card:GameCard,behavior:CardBehavior,trigger:CardTrigger,finalize:CardDestination|'none',controllerId=activePlayer.value,related?:CardReference){
    const actions=actionsFrom(behavior,trigger,source,controllerId,related),first=actions[0],optional=first?.type==='chooseCards'&&first.min===0||first?.type==='chooseOption'&&first.options.some(option=>option.actions.length===0);resolution.value={source,controllerId,sourceName:card.card.name,sourceCardNo:card.card.card_no,trigger,actions,cursor:0,bindings:{},related,finalize};if((behavior.oncePerTurnTriggers?.includes(trigger)||behavior.triggerLimitPerTurn?.[trigger])&&!optional)markTriggerUsed(resolution.value);log(`《${card.card.name}》的能力进入结算`);runResolution()
  }
  function sourceOnActiveField(instanceId:string){for(let slot=0;slot<active.value.battlefield.length;slot++){const field=active.value.battlefield[slot];if(field?.unit.instanceId===instanceId)return{playerId:activePlayer.value,zone:'battlefield' as const,instanceId,slot};const attachmentIndex=field?.equipment.findIndex(card=>card.instanceId===instanceId)??-1;if(attachmentIndex>=0)return{playerId:activePlayer.value,zone:'equipment' as const,instanceId,slot,attachmentIndex}}return null}
  function activatableAbilities(instanceId:string){const source=sourceOnActiveField(instanceId),card=source?cardAt(source):null,behavior=card?behaviorFor(card):undefined;if(!source||!card||!behavior?.activated||phase.value!=='主要阶段'||activePlayer.value!==source.playerId||halted.value||pendingChoice.value||resolution.value)return[];return behavior.activated.map(ability=>({id:ability.id,label:ability.label,disabled:Boolean(ability.requiresReady&&card.tapped||ability.oncePerTurn&&card.abilityUses[ability.id]===turnNumber.value||ability.oncePerGame&&card.abilityUses[ability.id]!==undefined)}))}
  function activateAbility(instanceId:string,abilityId:string){const source=sourceOnActiveField(instanceId),card=source?cardAt(source):null,behavior=card?behaviorFor(card):undefined,ability=behavior?.activated?.find(item=>item.id===abilityId);if(!source||!card||!behavior||!ability)return{ok:false,message:'找不到该启动能力'};if(phase.value!=='主要阶段'||halted.value||pendingChoice.value||resolution.value)return{ok:false,message:'当前不能发动启动能力'};if(ability.requiresReady&&card.tapped)return{ok:false,message:'该牌已经横置'};if(ability.oncePerTurn&&card.abilityUses[ability.id]===turnNumber.value)return{ok:false,message:'该能力本回合已经发动过'};if(ability.oncePerGame&&card.abilityUses[ability.id]!==undefined)return{ok:false,message:'该能力本局已经发动过'};for(const requirement of ability.requirements||[]){if(!conditionMet(requirement,activePlayer.value))return{ok:false,message:'不满足能力发动条件'}}const actions:ResolutionState['actions']=[],related=source.zone==='equipment'&&source.slot!==undefined?(()=>{const host=playerById(source.playerId).battlefield[source.slot!];return host?{playerId:source.playerId,zone:'battlefield' as const,instanceId:host.unit.instanceId,slot:source.slot}:undefined})():undefined;ability.activate(makeCardContext(source,activePlayer.value,actions,related));if(!actions.length)return{ok:false,message:'该能力尚未产生可结算动作'};card.abilityUses[ability.id]=turnNumber.value;resolution.value={source,controllerId:activePlayer.value,sourceName:card.card.name,sourceCardNo:card.card.card_no,actions,cursor:0,bindings:{},related,finalize:'none'};log(`发动《${card.card.name}》的启动能力：${ability.label}`);runResolution();return{ok:true,message:''}}
  function confirmChoice(instanceIds:string[]){
    const choice=pendingChoice.value,state=resolution.value;if(!choice||!state)return{ok:false,message:'当前没有等待选择的效果'};const unique=[...new Set(instanceIds)],allowed=choice.kind==='cards'?new Set(choice.options.map(option=>option.ref.instanceId)):new Set(choice.options.map(option=>option.id));if(unique.length<choice.min||unique.length>choice.max||unique.some(id=>!allowed.has(id)))return{ok:false,message:`请选择${choice.min===choice.max?choice.min:`${choice.min}至${choice.max}`}项合法内容`}
    const action=state.actions[state.cursor];if(choice.kind==='options'){if(!action||action.type!=='chooseOption')return{ok:false,message:'效果结算状态异常'};const next=action.options.filter(option=>unique.includes(option.id)).flatMap(option=>option.actions);if(next.length)markTriggerUsed(state);state.actions.splice(state.cursor,1,...next);pendingChoice.value=null;runResolution();return{ok:true,message:''}}
    if(!action||action.type!=='chooseCards')return{ok:false,message:'效果结算状态异常'};const chosenOptions=action.preserveSelectionOrder?unique.map(id=>choice.options.find(option=>option.ref.instanceId===id)!).filter(Boolean):choice.options.filter(option=>unique.includes(option.ref.instanceId)),effectiveCount=action.selector.zone==='signal'&&!action.physicalCards&&!action.preserveSelectionOrder?chosenOptions.reduce((sum,option)=>sum+(option.card.signalValueExpiresAtTurn===turnNumber.value?(option.card.signalValue||1):1),0):chosenOptions.length,optionalCost=isOptionalEnterCost(state,action);if((!optionalCost||effectiveCount>0)&&effectiveCount<action.min||effectiveCount>action.max)return{ok:false,message:`所选卡牌按效果计算后必须满足${action.min===action.max?action.min:`${action.min}至${action.max}`}张`};if(action.optionalExact&&effectiveCount!==0&&effectiveCount!==action.max)return{ok:false,message:`该可选代价必须不支付或完整支付${action.max}张`};if(action.allowedCounts&&!action.allowedCounts.includes(effectiveCount))return{ok:false,message:`只能选择相当于${action.allowedCounts.join('或')}张的卡牌`};if(action.constraint==='sameSignalColor'&&new Set(chosenOptions.map(option=>option.card.card.signal_color||option.card.card.features.match(/信号球·(.)/)?.[1]||'')).size>1)return{ok:false,message:'请选择同色信号球'};if(action.maxTotalCost!==undefined&&chosenOptions.reduce((sum,option)=>sum+(option.card.card.cost||0),0)>action.maxTotalCost)return{ok:false,message:`所选卡牌费用合计不能超过${action.maxTotalCost}`};const chosen=chosenOptions.map(option=>option.ref);state.bindings[action.bind]=chosen
    if(chosen.length)markTriggerUsed(state);if(action.remainder){const chosenSet=new Set(chosen.map(item=>item.instanceId)),pool=state.bindings[`${action.bind}__pool`]||[],remainder=pool.filter(item=>!chosenSet.has(item.instanceId));resolveRemainder(remainder,action.remainder)}
    state.actions.splice(state.cursor,1,...(chosen.length||action.min>0?action.then:[]));pendingChoice.value=null;runResolution();return{ok:true,message:''}
  }
  function start(deck1:CardRecord[],deck2:CardRecord[],mode:'standard'|'ordered'){
    players.value=[makePlayer('player1','玩家一'),makePlayer('player2','玩家二')];const first=deck1.map(instance),second=deck2.map(instance)
    players.value[0].deck=mode==='standard'?shuffle(first):first;players.value[1].deck=mode==='standard'?shuffle(second):second
    players.value.forEach(player=>{player.hand=player.deck.splice(0,4)})
    firstPlayer.value=randomPlayer();activePlayer.value=firstPlayer.value;phase.value='竖直阶段';turnNumber.value=1;started.value=true;gameStage.value='mulligan';mulliganStep.value=0;halted.value=false;fillAvailable.value=false;pendingChoice.value=null;resolution.value=null;chargeSequence.value=null;combat.value=null;endingTurn.value=false;triggerQueue.splice(0);logs.value=[]
    log(`随机决定${active.value.name}为先攻`);log(`双方各抽4张起始手牌，${active.value.name}先进行换牌`)
  }
  function confirmMulligan(instanceIds:string[]){
    if(gameStage.value!=='mulligan')return;const current=active.value,chosen=new Set(instanceIds),returned=current.hand.filter(card=>chosen.has(card.instanceId))
    current.hand=current.hand.filter(card=>!chosen.has(card.instanceId));current.hand.push(...current.deck.splice(0,returned.length));current.deck.push(...returned);current.deck=shuffle(current.deck);log(`${current.name}换回${returned.length}张手牌，抽取等量卡牌并洗切牌组`)
    if(mulliganStep.value===0){mulliganStep.value=1;activePlayer.value=firstPlayer.value==='player1'?'player2':'player1';log(`${active.value.name}开始换牌`);return}
    players.value.forEach(player=>{player.costZone=player.deck.splice(0,2);player.costZone.forEach(card=>{card.faceDown=false;card.tapped=false})});activePlayer.value=firstPlayer.value;gameStage.value='playing';phase.value='竖直阶段';log('双方换牌完成，各将牌组顶2张设置为起始明费');log(`${active.value.name}开始第一回合`)
  }
  function updateDeck(player:PlayerState){if(player.deck.length)return true;if(!player.graveyard.length){halted.value=true;log(`${player.name}的牌组与墓地同时为空，满足败北条件`);return false}player.deck=shuffle(player.graveyard.splice(0));player.erosion+=1;player.erosionChangedTurn=turnNumber.value;log(`${player.name}进行牌组更新，侵蚀增加至${player.erosion}/7`);if(player.erosion>=7){halted.value=true;log(`${player.name}侵蚀达到7，满足败北条件`);return false}return true}
  function canAttack(slot:number){const field=active.value.battlefield[slot];if(!field||phase.value!=='主要阶段'||gameStage.value!=='playing'||halted.value||resolution.value||pendingChoice.value||combat.value)return false;const continuous=continuousFor(field.unit,{playerId:activePlayer.value,zone:'battlefield',instanceId:field.unit.instanceId,slot},activePlayer.value),keywords=currentKeywords(activePlayer.value,slot);return!field.unit.tapped&&!continuous.cannotAttack&&!keywords.includes('不能攻击')&&(field.unit.enteredTurn<turnNumber.value||keywords.includes('速攻'))}
  function declareAttack(attackerSlot:number,targetSlot?:number){if(!canAttack(attackerSlot))return{ok:false,message:'该角色当前不能攻击'};const defender=opponent.value;if(targetSlot!==undefined){const target=defender.battlefield[targetSlot];if(!target)return{ok:false,message:'攻击目标不存在'};if(!target.unit.tapped)return{ok:false,message:'只能攻击对方横置角色或对方玩家'}}const attacker=active.value.battlefield[attackerSlot]!;attacker.unit.tapped=true;combat.value={attackerPlayerId:activePlayer.value,attackerSlot,targetPlayerId:defender.id,targetSlot:targetSlot??null,blockerSlot:null,stage:'attackTriggers',priorityPlayerId:defender.id,passes:0,preventDamage:false};const attackerRef:CardReference={playerId:activePlayer.value,zone:'battlefield',instanceId:attacker.unit.instanceId,slot:attackerSlot};log(`${active.value.name}以《${attacker.unit.card.name}》攻击${targetSlot===undefined?defender.name:`《${defender.battlefield[targetSlot]!.unit.card.name}》`}`);queueHostTriggers(attackerRef,'onAttack',attackerRef);drainTriggerQueue();continueSystemFlow();return{ok:true,message:''}}
  function openCombatResponse(){const state=combat.value;if(!state)return;state.stage='response';state.priorityPlayerId=state.targetPlayerId;state.passes=0;log(`进入攻击自由时点，${playerById(state.priorityPlayerId).name}获得优先权`)}
  function passCombatResponse(){const state=combat.value;if(!state||state.stage!=='response'||resolution.value||pendingChoice.value)return false;state.passes++;if(state.passes>=2){state.stage='block';log(`${playerById(state.targetPlayerId).name}可以选择1张竖直角色阻挡`)}else{state.priorityPlayerId=otherPlayerId(state.priorityPlayerId);log(`${playerById(state.priorityPlayerId).name}获得自由时点优先权`)}return true}
  function chooseBlock(slot?:number){const state=combat.value;if(!state||state.stage!=='block')return{ok:false,message:'当前不在阻挡步骤'};if(slot!==undefined){const field=playerById(state.targetPlayerId).battlefield[slot];if(!field||field.unit.tapped)return{ok:false,message:'只能选择竖直角色阻挡'};const continuous=continuousFor(field.unit,{playerId:state.targetPlayerId,zone:'battlefield',instanceId:field.unit.instanceId,slot},state.targetPlayerId),keywords=currentKeywords(state.targetPlayerId,slot),attacker=playerById(state.attackerPlayerId).battlefield[state.attackerSlot],attackContinuous=attacker?continuousFor(attacker.unit,{playerId:state.attackerPlayerId,zone:'battlefield',instanceId:attacker.unit.instanceId,slot:state.attackerSlot},state.attackerPlayerId):{},attackKeywords=attacker?currentKeywords(state.attackerPlayerId,state.attackerSlot):[];if(continuous.cannotBlock||keywords.includes('不能阻挡'))return{ok:false,message:'该角色不能阻挡'};const keywordLimit=attackKeywords.includes('PP5000以下不能阻挡')?5000:undefined,limit=attackContinuous.maxBlockerPp??keywordLimit;if(limit!==undefined&&currentPp(state.targetPlayerId,slot)<=limit)return{ok:false,message:`PP不高于${limit}的角色不能阻挡本次攻击`};field.unit.tapped=true;state.blockerSlot=slot;state.stage='blockTriggers';const blockerRef:CardReference={playerId:state.targetPlayerId,zone:'battlefield',instanceId:field.unit.instanceId,slot},attackerRef=attacker?{playerId:state.attackerPlayerId,zone:'battlefield' as const,instanceId:attacker.unit.instanceId,slot:state.attackerSlot}:undefined;log(`《${field.unit.card.name}》进行阻挡`);if(attackerRef)queueHostTriggers(blockerRef,'onBlock',attackerRef);const grantedKey='trigger:shieldCounter';if(attackerRef&&currentKeywords(state.targetPlayerId,slot).includes(SHIELD_COUNTER)&&field.unit.abilityUses[grantedKey]!==turnNumber.value){field.unit.abilityUses[grantedKey]=turnNumber.value;triggerQueue.push({source:blockerRef,card:field.unit,behavior:shieldCounterBehavior,trigger:'onBlock',controllerId:state.targetPlayerId,related:attackerRef})}drainTriggerQueue();continueSystemFlow()}else resolveCombat();return{ok:true,message:''}}
  function resolveCombat(){const state=combat.value;if(!state)return;const attackerField=playerById(state.attackerPlayerId).battlefield[state.attackerSlot];if(!attackerField){endCombat();return}const defender=playerById(state.targetPlayerId),defenderSlot=state.blockerSlot??state.targetSlot;if(defenderSlot!==null){const target=defender.battlefield[defenderSlot];if(target&&currentPp(state.attackerPlayerId,state.attackerSlot)>=currentPp(state.targetPlayerId,defenderSlot))destroyReferences([{playerId:state.targetPlayerId,zone:'battlefield',instanceId:target.unit.instanceId,slot:defenderSlot}]);endCombat();return}if(state.preventDamage){endCombat();return}state.stage='damageCharge';startCharge(state.targetPlayerId,Math.max(0,currentDp(state.attackerPlayerId,state.attackerSlot)),'damage','combatDamage')}
  function releaseCooperation(playerId:PlayerId,slot:number){const player=playerById(playerId),field=player.battlefield[slot],partner=field?.partner;if(!field||!partner)return;if(partner.card.card_no==='ST06-002'&&field.partnerFromZone==='hand'&&field.partnerFormedTurn===turnNumber.value)return;const origin=field.partnerFromZone,originalSlot=field.partnerOriginalSlot;field.partner=null;field.partnerFromZone=undefined;field.partnerOriginalSlot=undefined;field.partnerFormedTurn=undefined;if(origin==='battlefield'){const targetSlot=originalSlot!==undefined&&!player.battlefield[originalSlot]?originalSlot:player.battlefield.findIndex(item=>!item);if(targetSlot>=0)player.battlefield[targetSlot]={unit:partner,underCards:[],equipment:[],partner:null,modifiers:[]};else player.hand.push(partner)}else if(origin==='graveyard')player.graveyard.unshift(partner);else player.hand.push(partner);log(`《${partner.card.name}》解除协战状态`)}
  function endCombat(){const state=combat.value;if(state){const field=playerById(state.attackerPlayerId).battlefield[state.attackerSlot];if(field){const ref={playerId:state.attackerPlayerId,zone:'battlefield' as const,instanceId:field.unit.instanceId,slot:state.attackerSlot};queueHostTriggers(ref,'afterAttack',ref)}releaseCooperation(state.attackerPlayerId,state.attackerSlot);log('本次攻击结束')}combat.value=null;drainTriggerQueue()}
  function continueCharge(){
    const sequence=chargeSequence.value;if(!sequence||resolution.value||pendingChoice.value)return
    const player=playerById(sequence.playerId)
    while(sequence.remaining>0&&!halted.value){
      if(!updateDeck(player)){chargeSequence.value=null;return}
      const card=player.deck.shift();if(!card)break
      sequence.remaining--
      player.processingZone.push(card)
      const source:CardReference={playerId:player.id,zone:'processing',instanceId:card.instanceId}
      const signal=Boolean(card.card.signal_color)||card.card.card_types.includes('信号球牌')||card.card.name.includes('信号球')
      const attacker=combat.value?.stage==='attackCharge'&&combat.value.attackerPlayerId===player.id?player.battlefield[combat.value.attackerSlot]:null
      const attackerRef=attacker&&combat.value?{playerId:player.id,zone:'battlefield' as const,instanceId:attacker.unit.instanceId,slot:combat.value.attackerSlot}:null
      const behavior=behaviorFor(card),replacement=Boolean(attackerRef&&behavior?.processingReplacementFeature&&attacker?.unit.card.features.includes(behavior.processingReplacementFeature))
      log(`${player.name}${sequence.kind==='attack'?'攻击':'伤害'}充能翻开《${card.card.name}》`)
      const destination:CardDestination=replacement?'costTapped':signal?(sequence.kind==='attack'?'signalTop':'costFaceDown'):(sequence.kind==='attack'?'hand':'costFaceDown')
      const relatedRef:CardReference={playerId:player.id,zone:destination==='signalTop'?'signal':destination.startsWith('cost')?'cost':destination==='hand'?'hand':'processing',instanceId:card.instanceId}
      if(attackerRef)queueHostTriggers(attackerRef,'onAttackCharge',relatedRef)
      if(signal&&!replacement&&behavior?.onCharge){beginResolution(source,card,behavior,'onCharge',destination,player.id);return}
      moveReferences([source],destination)
      if(resolution.value||pendingChoice.value)return
    }
    if(sequence.remaining<=0){const after=sequence.after;if(sequence.kind==='damage'){player.erosion=Math.min(7,player.erosion+1);player.erosionChangedTurn=turnNumber.value;log(`${player.name}完成伤害充能，侵蚀增加至${player.erosion}/7`);if(player.erosion>=7){halted.value=true;log(`${player.name}侵蚀达到7，满足败北条件`)}}log(`${player.name}完成${sequence.kind==='attack'?'攻击':'伤害'}充能（${sequence.total}张）`);chargeSequence.value=null;if(after==='combatAttack')openCombatResponse();else if(after==='combatDamage')endCombat()}
  }
  function startCharge(playerId:PlayerId,amount:number,kind:'attack'|'damage',after?:'combatAttack'|'combatDamage'){if(amount<0||resolution.value||pendingChoice.value||chargeSequence.value)return false;chargeSequence.value={playerId,kind,remaining:amount,total:amount,after};continueCharge();return true}
  function draw(player:PlayerState,count:number){let actual=0;for(let i=0;i<count;i++){if(!updateDeck(player))break;const card=player.deck.shift();if(card){player.hand.push(card);actual++}}log(`${player.name}抽取${actual}张牌`)}
  function executeScheduledMoves(){for(const player of players.value){const refs:CardReference[]=[];const add=(cards:GameCard[],zone:CardReference['zone'])=>cards.forEach(card=>{if(card.scheduledMoves.some(move=>move.executeTurn<=turnNumber.value))refs.push({playerId:player.id,zone,instanceId:card.instanceId})});add(player.hand,'hand');add(player.deck,'deck');add(player.graveyard,'graveyard');add(player.costZone,'cost');add(player.signalZone,'signal');add(player.processingZone,'processing');player.battlefield.forEach((field,slot)=>{if(!field)return;if(field.unit.scheduledMoves.some(move=>move.executeTurn<=turnNumber.value))refs.push({playerId:player.id,zone:'battlefield',instanceId:field.unit.instanceId,slot});field.equipment.forEach((card,attachmentIndex)=>{if(card.scheduledMoves.some(move=>move.executeTurn<=turnNumber.value))refs.push({playerId:player.id,zone:'equipment',instanceId:card.instanceId,slot,attachmentIndex})})});for(const ref of refs){const card=cardAt(ref),scheduled=card?.scheduledMoves.find(move=>move.executeTurn<=turnNumber.value);if(!card||!scheduled)continue;card.scheduledMoves=card.scheduledMoves.filter(move=>move!==scheduled);moveReferences([ref],scheduled.destination)}}}
  function queueTurnEndTriggers(){const player=active.value;player.battlefield.forEach((field,slot)=>{if(!field)return;const host:CardReference={playerId:player.id,zone:'battlefield',instanceId:field.unit.instanceId,slot};queueTrigger(host,field.unit,'onTurnEnd',player.id,host);field.equipment.forEach((card,attachmentIndex)=>queueTrigger({playerId:player.id,zone:'equipment',instanceId:card.instanceId,slot,attachmentIndex},card,'onTurnEnd',player.id,host));if(field.partner)queueTrigger({playerId:player.id,zone:'partner',instanceId:field.partner.instanceId,slot},field.partner,'onTurnEnd',player.id,host)})}
  function completeTurn(){executeScheduledMoves();players.value.forEach(player=>{player.battlefield.forEach(field=>{if(field)field.modifiers=field.modifiers.filter(item=>item.expiresAtTurn!==turnNumber.value)});player.effects=player.effects.filter(effect=>effect.expiresAtTurn!==turnNumber.value)});endingTurn.value=false;activePlayer.value=activePlayer.value==='player1'?'player2':'player1';turnNumber.value++;phase.value='竖直阶段';log(`${active.value.name}成为回合玩家，进入竖直阶段`)}
  function advancePhase(){
    if(halted.value||pendingChoice.value||resolution.value||combat.value||gameStage.value!=='playing')return
    if(phase.value==='竖直阶段'){active.value.battlefield.forEach(slot=>{if(slot)slot.unit.tapped=false});active.value.costZone.forEach(card=>card.tapped=false);phase.value='抽牌填充阶段';const count=turnNumber.value===1?1:2;draw(active.value,count);fillAvailable.value=true;log(`进入抽牌填充阶段：抽${count}张牌，可将最多1张手牌作为明费`);return}
    if(phase.value==='抽牌填充阶段'){phase.value='主要阶段';fillAvailable.value=false;log('进入主要阶段');return}
    if(phase.value==='主要阶段'){phase.value='结束阶段';log('进入结束阶段');return}
    if(pendingDiscard.value>0){log(`手牌超过上限，仍需丢弃${pendingDiscard.value}张`);return}
    if(!endingTurn.value){endingTurn.value=true;queueTurnEndTriggers();drainTriggerQueue();continueSystemFlow()}
  }
  function fillCost(instanceId:string){if(gameStage.value!=='playing'||phase.value!=='抽牌填充阶段'||!fillAvailable.value)return false;const index=active.value.hand.findIndex(c=>c.instanceId===instanceId);if(index<0)return false;const [card]=active.value.hand.splice(index,1);if(active.value.costZone.length>=10){active.value.graveyard.unshift(card!);log('费用区达到上限，该牌改为进入墓地')}else{card!.faceDown=false;card!.tapped=false;active.value.costZone.push(card!);log(`${active.value.name}将《${card!.card.name}》正面竖直放入费用区`)}fillAvailable.value=false;return true}
  function discard(instanceId:string){if(phase.value!=='结束阶段'||pendingDiscard.value<=0)return false;const index=active.value.hand.findIndex(c=>c.instanceId===instanceId);if(index<0)return false;const [card]=active.value.hand.splice(index,1);active.value.graveyard.unshift(card!);log(`${active.value.name}丢弃《${card!.card.name}》`);return true}
  function legality(gameCard:GameCard){
    const reasons:string[]=[],card=gameCard.card,type=card.card_types,owner=players.value.find(player=>player.hand.some(item=>item.instanceId===gameCard.instanceId)),instant=type.includes('瞬时战术牌')
    if(gameStage.value!=='playing')reasons.push('仍在开局换牌阶段')
    if(halted.value)reasons.push('对局已经中断')
    if(pendingChoice.value||resolution.value)reasons.push('另一个卡牌效果正在结算')
    if(!owner)reasons.push('该牌不在任何玩家手牌中')
    if(instant){if(combat.value?.stage!=='response'||owner?.id!==combat.value.priorityPlayerId)reasons.push('只能由当前获得自由时点优先权的玩家使用')}
    else if(phase.value!=='主要阶段'||owner?.id!==activePlayer.value||combat.value)reasons.push('只能由回合玩家在主要阶段使用该牌')
    if(owner){const signal=Boolean(card.signal_color)||card.name.includes('信号球'),continuous=continuousFor(gameCard,{playerId:owner.id,zone:'hand',instanceId:gameCard.instanceId},owner.id);if(!signal&&!continuous.ignoreAttribute&&card.attribute&&!['无','空'].includes(card.attribute)&&!owner.costZone.some(c=>!c.faceDown&&c.card.attribute===card.attribute))reasons.push(`费用区没有${card.attribute}属性明费`);const cost=cardCost(gameCard,owner.id),available=owner.costZone.filter(item=>!item.tapped).length;if(available<cost)reasons.push(`可支付费用不足：需要${cost}，当前${available}`);if(isUpgradeCard(gameCard)){if(!upgradeTargets(gameCard,owner.id).length)reasons.push('没有满足升变条件的角色或明费上限不足')}else if((type.includes('角色牌')||type.includes('辅助机牌'))&&!owner.battlefield.some(slot=>slot===null))reasons.push('战场没有空余卡位');if(type.includes('装备牌')&&!owner.battlefield.some(Boolean))reasons.push('没有可以装备的角色');if(type.includes('战术牌'))reasons.push(...behaviorReasons(behaviorFor(gameCard),'onPlay',{playerId:owner.id,zone:'hand',instanceId:gameCard.instanceId},owner.id))}
    return [...new Set(reasons)]
  }
  function useFromHand(instanceId:string,costIds:string[],targetSlot?:number){
    const controller=players.value.find(player=>player.hand.some(card=>card.instanceId===instanceId));if(!controller)return{ok:false,message:'卡牌不在手牌'}
    const handIndex=controller.hand.findIndex(c=>c.instanceId===instanceId),gameCard=controller.hand[handIndex]!,reasons=legality(gameCard),cost=cardCost(gameCard,controller.id),unique=[...new Set(costIds)],selected=unique.map(id=>controller.costZone.find(c=>c.instanceId===id)).filter(Boolean) as GameCard[],upgrade=isUpgradeCard(gameCard)
    if(upgrade&&(targetSlot===undefined||!upgradeTargets(gameCard,controller.id).includes(targetSlot)))return{ok:false,message:'请选择满足条件的升变对象'}
    if(gameCard.card.card_types.includes('装备牌')){const field=targetSlot===undefined?null:controller.battlefield[targetSlot],hostContribution=field?continuousFor(field.unit,{playerId:controller.id,zone:'battlefield',instanceId:field.unit.instanceId,slot:targetSlot},controller.id):{},limit=hostContribution.equipmentLimit||1;if(!field||field.equipment.length>=limit)return{ok:false,message:`请选择仍可装备卡牌的角色（上限${limit}张）`}}
    if(gameCard.card.card_no==='BP01-040'&&!controller.battlefield.some(field=>field?.unit.card.name==='帕瓦'))reasons.push('升变需要我方战场1张《帕瓦》');if(reasons.length)return{ok:false,message:reasons.join('；')};if(selected.length!==cost||selected.some(c=>c.tapped))return{ok:false,message:`必须选择${cost}张竖直费用`}
    if(gameCard.card.card_no==='BP01-001'&&controller.costZone.filter(item=>!item.faceDown).length<8){const returned=controller.graveyard.filter(item=>item.card.features.includes('灰鸦小队')).slice(0,10),ids=new Set(returned.map(item=>item.instanceId));controller.graveyard=controller.graveyard.filter(item=>!ids.has(item.instanceId));controller.deck.push(...returned);controller.deck=shuffle(controller.deck);log(`${controller.name}将墓地10张〈灰鸦小队〉洗回牌组，无视费用上限升变条件`)}for(const fee of selected){if(fee.faceDown){controller.costZone=controller.costZone.filter(c=>c.instanceId!==fee.instanceId);controller.graveyard.unshift(fee)}else fee.tapped=true}
    controller.hand.splice(handIndex,1);const type=gameCard.card.card_types,behavior=behaviorFor(gameCard)
    const consumedEffect=controller.effects.find(effect=>effect.kind==='nextCostDiscount'&&(!effect.feature||gameCard.card.features.includes(effect.feature))&&(!effect.name||gameCard.card.name.includes(effect.name)));if(consumedEffect)controller.effects=controller.effects.filter(effect=>effect.id!==consumedEffect.id)
    if(upgrade){const slot=targetSlot!,field=controller.battlefield[slot]!;field.underCards.push(field.unit);field.unit=gameCard;gameCard.enteredTurn=turnNumber.value;gameCard.tapped=false;field.modifiers.push({id:crypto.randomUUID(),pp:0,dp:0,keywords:['速攻'],expiresAtTurn:turnNumber.value,sourceCardNo:gameCard.card.card_no});const entered={playerId:controller.id,zone:'battlefield' as const,instanceId:gameCard.instanceId,slot};log(`${controller.name}支付${cost}费，使《${gameCard.card.name}》升变出场`);if(behavior){queueTrigger(entered,gameCard,'onEnter',controller.id);queueOtherEnterTriggers(entered);drainTriggerQueue()}}
    else if(type.includes('装备牌')){const slot=targetSlot??-1;if(slot<0||!controller.battlefield[slot]){controller.hand.splice(handIndex,0,gameCard);return{ok:false,message:'请选择装备角色'}}controller.battlefield[slot]!.equipment.push(gameCard);controller.equipmentPlayedTurn=turnNumber.value;if(gameCard.card.name==='荣光护盾')controller.gloryShieldPlayedTurn=turnNumber.value;const source={playerId:controller.id,zone:'equipment' as const,instanceId:gameCard.instanceId,slot,attachmentIndex:controller.battlefield[slot]!.equipment.length-1},host={playerId:controller.id,zone:'battlefield' as const,instanceId:controller.battlefield[slot]!.unit.instanceId,slot};log(`${controller.name}支付${cost}费，将《${gameCard.card.name}》装备给《${controller.battlefield[slot]!.unit.card.name}》`);if(behavior?.onEnter)queueTrigger(source,gameCard,'onEnter',controller.id,host);else if(gameCard.card.effect&&!behavior){halted.value=true;log(`《${gameCard.card.name}》的装备能力尚未编码，等待人工处理`)}drainTriggerQueue()}
    else if(type.includes('角色牌')||type.includes('辅助机牌')){const slot=controller.battlefield.findIndex(item=>item===null);gameCard.enteredTurn=turnNumber.value;controller.battlefield[slot]={unit:gameCard,underCards:[],equipment:[],partner:null,modifiers:[]};const entered={playerId:controller.id,zone:'battlefield' as const,instanceId:gameCard.instanceId,slot};log(`${controller.name}支付${cost}费，使《${gameCard.card.name}》出场`);if(behavior){queueTrigger(entered,gameCard,'onEnter',controller.id);queueOtherEnterTriggers(entered);drainTriggerQueue()}else if(gameCard.card.effect){halted.value=true;log(`《${gameCard.card.name}》存在尚未编码的能力，等待人工处理`)}}
    else{controller.processingZone.push(gameCard);log(`${controller.name}支付${cost}费，使用《${gameCard.card.name}》`);if(behavior?.onPlay)beginResolution({playerId:controller.id,zone:'processing',instanceId:gameCard.instanceId},gameCard,behavior,'onPlay',behavior.finalizeOnPlay||'graveyard',controller.id);else{moveReferences([{playerId:controller.id,zone:'processing',instanceId:gameCard.instanceId}],'graveyard');if(gameCard.card.effect){halted.value=true;log('检测到尚未编码的卡牌效果，对局已保存现场并中断')}}}
    if(combat.value?.stage==='response'){combat.value.priorityPlayerId=otherPlayerId(controller.id);combat.value.passes=0;log(`${playerById(combat.value.priorityPlayerId).name}获得自由时点优先权`)}
    return{ok:true,message:''}
  }
  function resume(){halted.value=false;log('玩家确认人工处理完毕，对局继续')}
  return{players,activePlayer,firstPlayer,active,opponent,phase,turnNumber,started,gameStage,mulliganStep,revealOpponentHand,logs,fillAvailable,pendingDiscard,payableCosts,halted,pendingChoice,chargeSequence,combat,start,confirmMulligan,advancePhase,fillCost,discard,legality,useFromHand,confirmChoice,fieldStats,cardCost,upgradeTargets,activatableAbilities,activateAbility,startCharge,canAttack,declareAttack,passCombatResponse,chooseBlock,resume,log}
})
